// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: ProfileStore)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_profile_store.go -package mocks github.com/anstrom/scanorama/internal/api/handlers ProfileStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileStore is a mock of ProfileStore interface.
type MockProfileStore struct {
	ctrl     *gomock.Controller
	recorder *MockProfileStoreMockRecorder
	isgomock struct{}
}

// MockProfileStoreMockRecorder is the mock recorder for MockProfileStore.
type MockProfileStoreMockRecorder struct {
	mock *MockProfileStore
}

// NewMockProfileStore creates a new mock instance.
func NewMockProfileStore(ctrl *gomock.Controller) *MockProfileStore {
	mock := &MockProfileStore{ctrl: ctrl}
	mock.recorder = &MockProfileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileStore) EXPECT() *MockProfileStoreMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockProfileStore) CreateProfile(ctx context.Context, input db.CreateProfileInput) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, input)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileStoreMockRecorder) CreateProfile(ctx, input any) *MockProfileStoreCreateProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileStore)(nil).CreateProfile), ctx, input)
	return &MockProfileStoreCreateProfileCall{Call: call}
}

// MockProfileStoreCreateProfileCall wrap *gomock.Call
type MockProfileStoreCreateProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileStoreCreateProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockProfileStoreCreateProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileStoreCreateProfileCall) Do(f func(context.Context, db.CreateProfileInput) (*db.ScanProfile, error)) *MockProfileStoreCreateProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileStoreCreateProfileCall) DoAndReturn(f func(context.Context, db.CreateProfileInput) (*db.ScanProfile, error)) *MockProfileStoreCreateProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProfile mocks base method.
func (m *MockProfileStore) DeleteProfile(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockProfileStoreMockRecorder) DeleteProfile(ctx, id any) *MockProfileStoreDeleteProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockProfileStore)(nil).DeleteProfile), ctx, id)
	return &MockProfileStoreDeleteProfileCall{Call: call}
}

// MockProfileStoreDeleteProfileCall wrap *gomock.Call
type MockProfileStoreDeleteProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileStoreDeleteProfileCall) Return(arg0 error) *MockProfileStoreDeleteProfileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileStoreDeleteProfileCall) Do(f func(context.Context, string) error) *MockProfileStoreDeleteProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileStoreDeleteProfileCall) DoAndReturn(f func(context.Context, string) error) *MockProfileStoreDeleteProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProfile mocks base method.
func (m *MockProfileStore) GetProfile(ctx context.Context, id string) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, id)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileStoreMockRecorder) GetProfile(ctx, id any) *MockProfileStoreGetProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileStore)(nil).GetProfile), ctx, id)
	return &MockProfileStoreGetProfileCall{Call: call}
}

// MockProfileStoreGetProfileCall wrap *gomock.Call
type MockProfileStoreGetProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileStoreGetProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockProfileStoreGetProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileStoreGetProfileCall) Do(f func(context.Context, string) (*db.ScanProfile, error)) *MockProfileStoreGetProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileStoreGetProfileCall) DoAndReturn(f func(context.Context, string) (*db.ScanProfile, error)) *MockProfileStoreGetProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListProfiles mocks base method.
func (m *MockProfileStore) ListProfiles(ctx context.Context, filters db.ProfileFilters, offset, limit int) ([]*db.ScanProfile, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProfiles", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.ScanProfile)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProfiles indicates an expected call of ListProfiles.
func (mr *MockProfileStoreMockRecorder) ListProfiles(ctx, filters, offset, limit any) *MockProfileStoreListProfilesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfiles", reflect.TypeOf((*MockProfileStore)(nil).ListProfiles), ctx, filters, offset, limit)
	return &MockProfileStoreListProfilesCall{Call: call}
}

// MockProfileStoreListProfilesCall wrap *gomock.Call
type MockProfileStoreListProfilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileStoreListProfilesCall) Return(arg0 []*db.ScanProfile, arg1 int64, arg2 error) *MockProfileStoreListProfilesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileStoreListProfilesCall) Do(f func(context.Context, db.ProfileFilters, int, int) ([]*db.ScanProfile, int64, error)) *MockProfileStoreListProfilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileStoreListProfilesCall) DoAndReturn(f func(context.Context, db.ProfileFilters, int, int) ([]*db.ScanProfile, int64, error)) *MockProfileStoreListProfilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProfile mocks base method.
func (m *MockProfileStore) UpdateProfile(ctx context.Context, id string, input db.UpdateProfileInput) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, id, input)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileStoreMockRecorder) UpdateProfile(ctx, id, input any) *MockProfileStoreUpdateProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileStore)(nil).UpdateProfile), ctx, id, input)
	return &MockProfileStoreUpdateProfileCall{Call: call}
}

// MockProfileStoreUpdateProfileCall wrap *gomock.Call
type MockProfileStoreUpdateProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileStoreUpdateProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockProfileStoreUpdateProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileStoreUpdateProfileCall) Do(f func(context.Context, string, db.UpdateProfileInput) (*db.ScanProfile, error)) *MockProfileStoreUpdateProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileStoreUpdateProfileCall) DoAndReturn(f func(context.Context, string, db.UpdateProfileInput) (*db.ScanProfile, error)) *MockProfileStoreUpdateProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
