// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: HostStore)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_host_store.go -package mocks github.com/anstrom/scanorama/internal/api/handlers HostStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockHostStore is a mock of HostStore interface.
type MockHostStore struct {
	ctrl     *gomock.Controller
	recorder *MockHostStoreMockRecorder
	isgomock struct{}
}

// MockHostStoreMockRecorder is the mock recorder for MockHostStore.
type MockHostStoreMockRecorder struct {
	mock *MockHostStore
}

// NewMockHostStore creates a new mock instance.
func NewMockHostStore(ctrl *gomock.Controller) *MockHostStore {
	mock := &MockHostStore{ctrl: ctrl}
	mock.recorder = &MockHostStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostStore) EXPECT() *MockHostStoreMockRecorder {
	return m.recorder
}

// CreateHost mocks base method.
func (m *MockHostStore) CreateHost(ctx context.Context, hostData any) (*db.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHost", ctx, hostData)
	ret0, _ := ret[0].(*db.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHost indicates an expected call of CreateHost.
func (mr *MockHostStoreMockRecorder) CreateHost(ctx, hostData any) *MockHostStoreCreateHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHost", reflect.TypeOf((*MockHostStore)(nil).CreateHost), ctx, hostData)
	return &MockHostStoreCreateHostCall{Call: call}
}

// MockHostStoreCreateHostCall wrap *gomock.Call
type MockHostStoreCreateHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostStoreCreateHostCall) Return(arg0 *db.Host, arg1 error) *MockHostStoreCreateHostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostStoreCreateHostCall) Do(f func(context.Context, any) (*db.Host, error)) *MockHostStoreCreateHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostStoreCreateHostCall) DoAndReturn(f func(context.Context, any) (*db.Host, error)) *MockHostStoreCreateHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteHost mocks base method.
func (m *MockHostStore) DeleteHost(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHost", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHost indicates an expected call of DeleteHost.
func (mr *MockHostStoreMockRecorder) DeleteHost(ctx, id any) *MockHostStoreDeleteHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHost", reflect.TypeOf((*MockHostStore)(nil).DeleteHost), ctx, id)
	return &MockHostStoreDeleteHostCall{Call: call}
}

// MockHostStoreDeleteHostCall wrap *gomock.Call
type MockHostStoreDeleteHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostStoreDeleteHostCall) Return(arg0 error) *MockHostStoreDeleteHostCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostStoreDeleteHostCall) Do(f func(context.Context, uuid.UUID) error) *MockHostStoreDeleteHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostStoreDeleteHostCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockHostStoreDeleteHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHost mocks base method.
func (m *MockHostStore) GetHost(ctx context.Context, id uuid.UUID) (*db.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost", ctx, id)
	ret0, _ := ret[0].(*db.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHost indicates an expected call of GetHost.
func (mr *MockHostStoreMockRecorder) GetHost(ctx, id any) *MockHostStoreGetHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockHostStore)(nil).GetHost), ctx, id)
	return &MockHostStoreGetHostCall{Call: call}
}

// MockHostStoreGetHostCall wrap *gomock.Call
type MockHostStoreGetHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostStoreGetHostCall) Return(arg0 *db.Host, arg1 error) *MockHostStoreGetHostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostStoreGetHostCall) Do(f func(context.Context, uuid.UUID) (*db.Host, error)) *MockHostStoreGetHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostStoreGetHostCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.Host, error)) *MockHostStoreGetHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHostScans mocks base method.
func (m *MockHostStore) GetHostScans(ctx context.Context, hostID uuid.UUID, offset, limit int) ([]*db.Scan, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostScans", ctx, hostID, offset, limit)
	ret0, _ := ret[0].([]*db.Scan)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHostScans indicates an expected call of GetHostScans.
func (mr *MockHostStoreMockRecorder) GetHostScans(ctx, hostID, offset, limit any) *MockHostStoreGetHostScansCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostScans", reflect.TypeOf((*MockHostStore)(nil).GetHostScans), ctx, hostID, offset, limit)
	return &MockHostStoreGetHostScansCall{Call: call}
}

// MockHostStoreGetHostScansCall wrap *gomock.Call
type MockHostStoreGetHostScansCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostStoreGetHostScansCall) Return(arg0 []*db.Scan, arg1 int64, arg2 error) *MockHostStoreGetHostScansCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostStoreGetHostScansCall) Do(f func(context.Context, uuid.UUID, int, int) ([]*db.Scan, int64, error)) *MockHostStoreGetHostScansCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostStoreGetHostScansCall) DoAndReturn(f func(context.Context, uuid.UUID, int, int) ([]*db.Scan, int64, error)) *MockHostStoreGetHostScansCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListHosts mocks base method.
func (m *MockHostStore) ListHosts(ctx context.Context, filters *db.HostFilters, offset, limit int) ([]*db.Host, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHosts", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.Host)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListHosts indicates an expected call of ListHosts.
func (mr *MockHostStoreMockRecorder) ListHosts(ctx, filters, offset, limit any) *MockHostStoreListHostsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHosts", reflect.TypeOf((*MockHostStore)(nil).ListHosts), ctx, filters, offset, limit)
	return &MockHostStoreListHostsCall{Call: call}
}

// MockHostStoreListHostsCall wrap *gomock.Call
type MockHostStoreListHostsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostStoreListHostsCall) Return(arg0 []*db.Host, arg1 int64, arg2 error) *MockHostStoreListHostsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostStoreListHostsCall) Do(f func(context.Context, *db.HostFilters, int, int) ([]*db.Host, int64, error)) *MockHostStoreListHostsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostStoreListHostsCall) DoAndReturn(f func(context.Context, *db.HostFilters, int, int) ([]*db.Host, int64, error)) *MockHostStoreListHostsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateHost mocks base method.
func (m *MockHostStore) UpdateHost(ctx context.Context, id uuid.UUID, hostData any) (*db.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHost", ctx, id, hostData)
	ret0, _ := ret[0].(*db.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHost indicates an expected call of UpdateHost.
func (mr *MockHostStoreMockRecorder) UpdateHost(ctx, id, hostData any) *MockHostStoreUpdateHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHost", reflect.TypeOf((*MockHostStore)(nil).UpdateHost), ctx, id, hostData)
	return &MockHostStoreUpdateHostCall{Call: call}
}

// MockHostStoreUpdateHostCall wrap *gomock.Call
type MockHostStoreUpdateHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostStoreUpdateHostCall) Return(arg0 *db.Host, arg1 error) *MockHostStoreUpdateHostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostStoreUpdateHostCall) Do(f func(context.Context, uuid.UUID, any) (*db.Host, error)) *MockHostStoreUpdateHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostStoreUpdateHostCall) DoAndReturn(f func(context.Context, uuid.UUID, any) (*db.Host, error)) *MockHostStoreUpdateHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
