// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: ScheduleServicer)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_schedule_servicer.go -package mocks github.com/anstrom/scanorama/internal/api/handlers ScheduleServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleServicer is a mock of ScheduleServicer interface.
type MockScheduleServicer struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleServicerMockRecorder
	isgomock struct{}
}

// MockScheduleServicerMockRecorder is the mock recorder for MockScheduleServicer.
type MockScheduleServicerMockRecorder struct {
	mock *MockScheduleServicer
}

// NewMockScheduleServicer creates a new mock instance.
func NewMockScheduleServicer(ctrl *gomock.Controller) *MockScheduleServicer {
	mock := &MockScheduleServicer{ctrl: ctrl}
	mock.recorder = &MockScheduleServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleServicer) EXPECT() *MockScheduleServicerMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockScheduleServicer) CreateSchedule(ctx context.Context, input db.CreateScheduleInput) (*db.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, input)
	ret0, _ := ret[0].(*db.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleServicerMockRecorder) CreateSchedule(ctx, input any) *MockScheduleServicerCreateScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleServicer)(nil).CreateSchedule), ctx, input)
	return &MockScheduleServicerCreateScheduleCall{Call: call}
}

// MockScheduleServicerCreateScheduleCall wrap *gomock.Call
type MockScheduleServicerCreateScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerCreateScheduleCall) Return(arg0 *db.Schedule, arg1 error) *MockScheduleServicerCreateScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerCreateScheduleCall) Do(f func(context.Context, db.CreateScheduleInput) (*db.Schedule, error)) *MockScheduleServicerCreateScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerCreateScheduleCall) DoAndReturn(f func(context.Context, db.CreateScheduleInput) (*db.Schedule, error)) *MockScheduleServicerCreateScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSchedule mocks base method.
func (m *MockScheduleServicer) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockScheduleServicerMockRecorder) DeleteSchedule(ctx, id any) *MockScheduleServicerDeleteScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockScheduleServicer)(nil).DeleteSchedule), ctx, id)
	return &MockScheduleServicerDeleteScheduleCall{Call: call}
}

// MockScheduleServicerDeleteScheduleCall wrap *gomock.Call
type MockScheduleServicerDeleteScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerDeleteScheduleCall) Return(arg0 error) *MockScheduleServicerDeleteScheduleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerDeleteScheduleCall) Do(f func(context.Context, uuid.UUID) error) *MockScheduleServicerDeleteScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerDeleteScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScheduleServicerDeleteScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DisableSchedule mocks base method.
func (m *MockScheduleServicer) DisableSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableSchedule indicates an expected call of DisableSchedule.
func (mr *MockScheduleServicerMockRecorder) DisableSchedule(ctx, id any) *MockScheduleServicerDisableScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableSchedule", reflect.TypeOf((*MockScheduleServicer)(nil).DisableSchedule), ctx, id)
	return &MockScheduleServicerDisableScheduleCall{Call: call}
}

// MockScheduleServicerDisableScheduleCall wrap *gomock.Call
type MockScheduleServicerDisableScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerDisableScheduleCall) Return(arg0 error) *MockScheduleServicerDisableScheduleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerDisableScheduleCall) Do(f func(context.Context, uuid.UUID) error) *MockScheduleServicerDisableScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerDisableScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScheduleServicerDisableScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EnableSchedule mocks base method.
func (m *MockScheduleServicer) EnableSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableSchedule indicates an expected call of EnableSchedule.
func (mr *MockScheduleServicerMockRecorder) EnableSchedule(ctx, id any) *MockScheduleServicerEnableScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableSchedule", reflect.TypeOf((*MockScheduleServicer)(nil).EnableSchedule), ctx, id)
	return &MockScheduleServicerEnableScheduleCall{Call: call}
}

// MockScheduleServicerEnableScheduleCall wrap *gomock.Call
type MockScheduleServicerEnableScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerEnableScheduleCall) Return(arg0 error) *MockScheduleServicerEnableScheduleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerEnableScheduleCall) Do(f func(context.Context, uuid.UUID) error) *MockScheduleServicerEnableScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerEnableScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScheduleServicerEnableScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSchedule mocks base method.
func (m *MockScheduleServicer) GetSchedule(ctx context.Context, id uuid.UUID) (*db.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedule", ctx, id)
	ret0, _ := ret[0].(*db.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedule indicates an expected call of GetSchedule.
func (mr *MockScheduleServicerMockRecorder) GetSchedule(ctx, id any) *MockScheduleServicerGetScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedule", reflect.TypeOf((*MockScheduleServicer)(nil).GetSchedule), ctx, id)
	return &MockScheduleServicerGetScheduleCall{Call: call}
}

// MockScheduleServicerGetScheduleCall wrap *gomock.Call
type MockScheduleServicerGetScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerGetScheduleCall) Return(arg0 *db.Schedule, arg1 error) *MockScheduleServicerGetScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerGetScheduleCall) Do(f func(context.Context, uuid.UUID) (*db.Schedule, error)) *MockScheduleServicerGetScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerGetScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.Schedule, error)) *MockScheduleServicerGetScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSchedules mocks base method.
func (m *MockScheduleServicer) ListSchedules(ctx context.Context, filters db.ScheduleFilters, offset, limit int) ([]*db.Schedule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.Schedule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockScheduleServicerMockRecorder) ListSchedules(ctx, filters, offset, limit any) *MockScheduleServicerListSchedulesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockScheduleServicer)(nil).ListSchedules), ctx, filters, offset, limit)
	return &MockScheduleServicerListSchedulesCall{Call: call}
}

// MockScheduleServicerListSchedulesCall wrap *gomock.Call
type MockScheduleServicerListSchedulesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerListSchedulesCall) Return(arg0 []*db.Schedule, arg1 int64, arg2 error) *MockScheduleServicerListSchedulesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerListSchedulesCall) Do(f func(context.Context, db.ScheduleFilters, int, int) ([]*db.Schedule, int64, error)) *MockScheduleServicerListSchedulesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerListSchedulesCall) DoAndReturn(f func(context.Context, db.ScheduleFilters, int, int) ([]*db.Schedule, int64, error)) *MockScheduleServicerListSchedulesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NextRun mocks base method.
func (m *MockScheduleServicer) NextRun(ctx context.Context, id uuid.UUID) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextRun", ctx, id)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextRun indicates an expected call of NextRun.
func (mr *MockScheduleServicerMockRecorder) NextRun(ctx, id any) *MockScheduleServicerNextRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextRun", reflect.TypeOf((*MockScheduleServicer)(nil).NextRun), ctx, id)
	return &MockScheduleServicerNextRunCall{Call: call}
}

// MockScheduleServicerNextRunCall wrap *gomock.Call
type MockScheduleServicerNextRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerNextRunCall) Return(arg0 time.Time, arg1 error) *MockScheduleServicerNextRunCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerNextRunCall) Do(f func(context.Context, uuid.UUID) (time.Time, error)) *MockScheduleServicerNextRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerNextRunCall) DoAndReturn(f func(context.Context, uuid.UUID) (time.Time, error)) *MockScheduleServicerNextRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateSchedule mocks base method.
func (m *MockScheduleServicer) UpdateSchedule(ctx context.Context, id uuid.UUID, input db.UpdateScheduleInput) (*db.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", ctx, id, input)
	ret0, _ := ret[0].(*db.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockScheduleServicerMockRecorder) UpdateSchedule(ctx, id, input any) *MockScheduleServicerUpdateScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockScheduleServicer)(nil).UpdateSchedule), ctx, id, input)
	return &MockScheduleServicerUpdateScheduleCall{Call: call}
}

// MockScheduleServicerUpdateScheduleCall wrap *gomock.Call
type MockScheduleServicerUpdateScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleServicerUpdateScheduleCall) Return(arg0 *db.Schedule, arg1 error) *MockScheduleServicerUpdateScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleServicerUpdateScheduleCall) Do(f func(context.Context, uuid.UUID, db.UpdateScheduleInput) (*db.Schedule, error)) *MockScheduleServicerUpdateScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleServicerUpdateScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID, db.UpdateScheduleInput) (*db.Schedule, error)) *MockScheduleServicerUpdateScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
