// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: DeviceServicer)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_device_servicer.go -package mocks github.com/anstrom/scanorama/internal/api/handlers DeviceServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceServicer is a mock of DeviceServicer interface.
type MockDeviceServicer struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceServicerMockRecorder
	isgomock struct{}
}

// MockDeviceServicerMockRecorder is the mock recorder for MockDeviceServicer.
type MockDeviceServicerMockRecorder struct {
	mock *MockDeviceServicer
}

// NewMockDeviceServicer creates a new mock instance.
func NewMockDeviceServicer(ctrl *gomock.Controller) *MockDeviceServicer {
	mock := &MockDeviceServicer{ctrl: ctrl}
	mock.recorder = &MockDeviceServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceServicer) EXPECT() *MockDeviceServicerMockRecorder {
	return m.recorder
}

// AcceptSuggestion mocks base method.
func (m *MockDeviceServicer) AcceptSuggestion(ctx context.Context, suggestionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptSuggestion", ctx, suggestionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptSuggestion indicates an expected call of AcceptSuggestion.
func (mr *MockDeviceServicerMockRecorder) AcceptSuggestion(ctx, suggestionID any) *MockDeviceServicerAcceptSuggestionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptSuggestion", reflect.TypeOf((*MockDeviceServicer)(nil).AcceptSuggestion), ctx, suggestionID)
	return &MockDeviceServicerAcceptSuggestionCall{Call: call}
}

// MockDeviceServicerAcceptSuggestionCall wrap *gomock.Call
type MockDeviceServicerAcceptSuggestionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerAcceptSuggestionCall) Return(arg0 error) *MockDeviceServicerAcceptSuggestionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerAcceptSuggestionCall) Do(f func(context.Context, uuid.UUID) error) *MockDeviceServicerAcceptSuggestionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerAcceptSuggestionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockDeviceServicerAcceptSuggestionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AttachHost mocks base method.
func (m *MockDeviceServicer) AttachHost(ctx context.Context, deviceID, hostID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachHost", ctx, deviceID, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachHost indicates an expected call of AttachHost.
func (mr *MockDeviceServicerMockRecorder) AttachHost(ctx, deviceID, hostID any) *MockDeviceServicerAttachHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachHost", reflect.TypeOf((*MockDeviceServicer)(nil).AttachHost), ctx, deviceID, hostID)
	return &MockDeviceServicerAttachHostCall{Call: call}
}

// MockDeviceServicerAttachHostCall wrap *gomock.Call
type MockDeviceServicerAttachHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerAttachHostCall) Return(arg0 error) *MockDeviceServicerAttachHostCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerAttachHostCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockDeviceServicerAttachHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerAttachHostCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockDeviceServicerAttachHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateDevice mocks base method.
func (m *MockDeviceServicer) CreateDevice(ctx context.Context, input db.CreateDeviceInput) (*db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDevice", ctx, input)
	ret0, _ := ret[0].(*db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDevice indicates an expected call of CreateDevice.
func (mr *MockDeviceServicerMockRecorder) CreateDevice(ctx, input any) *MockDeviceServicerCreateDeviceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDevice", reflect.TypeOf((*MockDeviceServicer)(nil).CreateDevice), ctx, input)
	return &MockDeviceServicerCreateDeviceCall{Call: call}
}

// MockDeviceServicerCreateDeviceCall wrap *gomock.Call
type MockDeviceServicerCreateDeviceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerCreateDeviceCall) Return(arg0 *db.Device, arg1 error) *MockDeviceServicerCreateDeviceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerCreateDeviceCall) Do(f func(context.Context, db.CreateDeviceInput) (*db.Device, error)) *MockDeviceServicerCreateDeviceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerCreateDeviceCall) DoAndReturn(f func(context.Context, db.CreateDeviceInput) (*db.Device, error)) *MockDeviceServicerCreateDeviceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteDevice mocks base method.
func (m *MockDeviceServicer) DeleteDevice(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDevice", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDevice indicates an expected call of DeleteDevice.
func (mr *MockDeviceServicerMockRecorder) DeleteDevice(ctx, id any) *MockDeviceServicerDeleteDeviceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDevice", reflect.TypeOf((*MockDeviceServicer)(nil).DeleteDevice), ctx, id)
	return &MockDeviceServicerDeleteDeviceCall{Call: call}
}

// MockDeviceServicerDeleteDeviceCall wrap *gomock.Call
type MockDeviceServicerDeleteDeviceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerDeleteDeviceCall) Return(arg0 error) *MockDeviceServicerDeleteDeviceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerDeleteDeviceCall) Do(f func(context.Context, uuid.UUID) error) *MockDeviceServicerDeleteDeviceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerDeleteDeviceCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockDeviceServicerDeleteDeviceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetachHost mocks base method.
func (m *MockDeviceServicer) DetachHost(ctx context.Context, deviceID, hostID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachHost", ctx, deviceID, hostID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachHost indicates an expected call of DetachHost.
func (mr *MockDeviceServicerMockRecorder) DetachHost(ctx, deviceID, hostID any) *MockDeviceServicerDetachHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachHost", reflect.TypeOf((*MockDeviceServicer)(nil).DetachHost), ctx, deviceID, hostID)
	return &MockDeviceServicerDetachHostCall{Call: call}
}

// MockDeviceServicerDetachHostCall wrap *gomock.Call
type MockDeviceServicerDetachHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerDetachHostCall) Return(arg0 error) *MockDeviceServicerDetachHostCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerDetachHostCall) Do(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockDeviceServicerDetachHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerDetachHostCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID) error) *MockDeviceServicerDetachHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DismissSuggestion mocks base method.
func (m *MockDeviceServicer) DismissSuggestion(ctx context.Context, suggestionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DismissSuggestion", ctx, suggestionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DismissSuggestion indicates an expected call of DismissSuggestion.
func (mr *MockDeviceServicerMockRecorder) DismissSuggestion(ctx, suggestionID any) *MockDeviceServicerDismissSuggestionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DismissSuggestion", reflect.TypeOf((*MockDeviceServicer)(nil).DismissSuggestion), ctx, suggestionID)
	return &MockDeviceServicerDismissSuggestionCall{Call: call}
}

// MockDeviceServicerDismissSuggestionCall wrap *gomock.Call
type MockDeviceServicerDismissSuggestionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerDismissSuggestionCall) Return(arg0 error) *MockDeviceServicerDismissSuggestionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerDismissSuggestionCall) Do(f func(context.Context, uuid.UUID) error) *MockDeviceServicerDismissSuggestionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerDismissSuggestionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockDeviceServicerDismissSuggestionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDeviceDetail mocks base method.
func (m *MockDeviceServicer) GetDeviceDetail(ctx context.Context, id uuid.UUID) (*db.DeviceDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceDetail", ctx, id)
	ret0, _ := ret[0].(*db.DeviceDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceDetail indicates an expected call of GetDeviceDetail.
func (mr *MockDeviceServicerMockRecorder) GetDeviceDetail(ctx, id any) *MockDeviceServicerGetDeviceDetailCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceDetail", reflect.TypeOf((*MockDeviceServicer)(nil).GetDeviceDetail), ctx, id)
	return &MockDeviceServicerGetDeviceDetailCall{Call: call}
}

// MockDeviceServicerGetDeviceDetailCall wrap *gomock.Call
type MockDeviceServicerGetDeviceDetailCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerGetDeviceDetailCall) Return(arg0 *db.DeviceDetail, arg1 error) *MockDeviceServicerGetDeviceDetailCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerGetDeviceDetailCall) Do(f func(context.Context, uuid.UUID) (*db.DeviceDetail, error)) *MockDeviceServicerGetDeviceDetailCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerGetDeviceDetailCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.DeviceDetail, error)) *MockDeviceServicerGetDeviceDetailCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDevices mocks base method.
func (m *MockDeviceServicer) ListDevices(ctx context.Context) ([]db.DeviceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevices", ctx)
	ret0, _ := ret[0].([]db.DeviceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockDeviceServicerMockRecorder) ListDevices(ctx any) *MockDeviceServicerListDevicesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockDeviceServicer)(nil).ListDevices), ctx)
	return &MockDeviceServicerListDevicesCall{Call: call}
}

// MockDeviceServicerListDevicesCall wrap *gomock.Call
type MockDeviceServicerListDevicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerListDevicesCall) Return(arg0 []db.DeviceSummary, arg1 error) *MockDeviceServicerListDevicesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerListDevicesCall) Do(f func(context.Context) ([]db.DeviceSummary, error)) *MockDeviceServicerListDevicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerListDevicesCall) DoAndReturn(f func(context.Context) ([]db.DeviceSummary, error)) *MockDeviceServicerListDevicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDevice mocks base method.
func (m *MockDeviceServicer) UpdateDevice(ctx context.Context, id uuid.UUID, input db.UpdateDeviceInput) (*db.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", ctx, id, input)
	ret0, _ := ret[0].(*db.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockDeviceServicerMockRecorder) UpdateDevice(ctx, id, input any) *MockDeviceServicerUpdateDeviceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockDeviceServicer)(nil).UpdateDevice), ctx, id, input)
	return &MockDeviceServicerUpdateDeviceCall{Call: call}
}

// MockDeviceServicerUpdateDeviceCall wrap *gomock.Call
type MockDeviceServicerUpdateDeviceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeviceServicerUpdateDeviceCall) Return(arg0 *db.Device, arg1 error) *MockDeviceServicerUpdateDeviceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeviceServicerUpdateDeviceCall) Do(f func(context.Context, uuid.UUID, db.UpdateDeviceInput) (*db.Device, error)) *MockDeviceServicerUpdateDeviceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeviceServicerUpdateDeviceCall) DoAndReturn(f func(context.Context, uuid.UUID, db.UpdateDeviceInput) (*db.Device, error)) *MockDeviceServicerUpdateDeviceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
