// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: ProfileServicer)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_profile_servicer.go -package mocks github.com/anstrom/scanorama/internal/api/handlers ProfileServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileServicer is a mock of ProfileServicer interface.
type MockProfileServicer struct {
	ctrl     *gomock.Controller
	recorder *MockProfileServicerMockRecorder
	isgomock struct{}
}

// MockProfileServicerMockRecorder is the mock recorder for MockProfileServicer.
type MockProfileServicerMockRecorder struct {
	mock *MockProfileServicer
}

// NewMockProfileServicer creates a new mock instance.
func NewMockProfileServicer(ctrl *gomock.Controller) *MockProfileServicer {
	mock := &MockProfileServicer{ctrl: ctrl}
	mock.recorder = &MockProfileServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileServicer) EXPECT() *MockProfileServicerMockRecorder {
	return m.recorder
}

// CloneProfile mocks base method.
func (m *MockProfileServicer) CloneProfile(ctx context.Context, fromID, newName string) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneProfile", ctx, fromID, newName)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneProfile indicates an expected call of CloneProfile.
func (mr *MockProfileServicerMockRecorder) CloneProfile(ctx, fromID, newName any) *MockProfileServicerCloneProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneProfile", reflect.TypeOf((*MockProfileServicer)(nil).CloneProfile), ctx, fromID, newName)
	return &MockProfileServicerCloneProfileCall{Call: call}
}

// MockProfileServicerCloneProfileCall wrap *gomock.Call
type MockProfileServicerCloneProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileServicerCloneProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockProfileServicerCloneProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileServicerCloneProfileCall) Do(f func(context.Context, string, string) (*db.ScanProfile, error)) *MockProfileServicerCloneProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileServicerCloneProfileCall) DoAndReturn(f func(context.Context, string, string) (*db.ScanProfile, error)) *MockProfileServicerCloneProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateProfile mocks base method.
func (m *MockProfileServicer) CreateProfile(ctx context.Context, input db.CreateProfileInput) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, input)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileServicerMockRecorder) CreateProfile(ctx, input any) *MockProfileServicerCreateProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileServicer)(nil).CreateProfile), ctx, input)
	return &MockProfileServicerCreateProfileCall{Call: call}
}

// MockProfileServicerCreateProfileCall wrap *gomock.Call
type MockProfileServicerCreateProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileServicerCreateProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockProfileServicerCreateProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileServicerCreateProfileCall) Do(f func(context.Context, db.CreateProfileInput) (*db.ScanProfile, error)) *MockProfileServicerCreateProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileServicerCreateProfileCall) DoAndReturn(f func(context.Context, db.CreateProfileInput) (*db.ScanProfile, error)) *MockProfileServicerCreateProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteProfile mocks base method.
func (m *MockProfileServicer) DeleteProfile(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfile", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProfile indicates an expected call of DeleteProfile.
func (mr *MockProfileServicerMockRecorder) DeleteProfile(ctx, id any) *MockProfileServicerDeleteProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfile", reflect.TypeOf((*MockProfileServicer)(nil).DeleteProfile), ctx, id)
	return &MockProfileServicerDeleteProfileCall{Call: call}
}

// MockProfileServicerDeleteProfileCall wrap *gomock.Call
type MockProfileServicerDeleteProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileServicerDeleteProfileCall) Return(arg0 error) *MockProfileServicerDeleteProfileCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileServicerDeleteProfileCall) Do(f func(context.Context, string) error) *MockProfileServicerDeleteProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileServicerDeleteProfileCall) DoAndReturn(f func(context.Context, string) error) *MockProfileServicerDeleteProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProfile mocks base method.
func (m *MockProfileServicer) GetProfile(ctx context.Context, id string) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, id)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileServicerMockRecorder) GetProfile(ctx, id any) *MockProfileServicerGetProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileServicer)(nil).GetProfile), ctx, id)
	return &MockProfileServicerGetProfileCall{Call: call}
}

// MockProfileServicerGetProfileCall wrap *gomock.Call
type MockProfileServicerGetProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileServicerGetProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockProfileServicerGetProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileServicerGetProfileCall) Do(f func(context.Context, string) (*db.ScanProfile, error)) *MockProfileServicerGetProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileServicerGetProfileCall) DoAndReturn(f func(context.Context, string) (*db.ScanProfile, error)) *MockProfileServicerGetProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListProfiles mocks base method.
func (m *MockProfileServicer) ListProfiles(ctx context.Context, filters db.ProfileFilters, offset, limit int) ([]*db.ScanProfile, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProfiles", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.ScanProfile)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListProfiles indicates an expected call of ListProfiles.
func (mr *MockProfileServicerMockRecorder) ListProfiles(ctx, filters, offset, limit any) *MockProfileServicerListProfilesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProfiles", reflect.TypeOf((*MockProfileServicer)(nil).ListProfiles), ctx, filters, offset, limit)
	return &MockProfileServicerListProfilesCall{Call: call}
}

// MockProfileServicerListProfilesCall wrap *gomock.Call
type MockProfileServicerListProfilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileServicerListProfilesCall) Return(arg0 []*db.ScanProfile, arg1 int64, arg2 error) *MockProfileServicerListProfilesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileServicerListProfilesCall) Do(f func(context.Context, db.ProfileFilters, int, int) ([]*db.ScanProfile, int64, error)) *MockProfileServicerListProfilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileServicerListProfilesCall) DoAndReturn(f func(context.Context, db.ProfileFilters, int, int) ([]*db.ScanProfile, int64, error)) *MockProfileServicerListProfilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProfile mocks base method.
func (m *MockProfileServicer) UpdateProfile(ctx context.Context, id string, input db.UpdateProfileInput) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, id, input)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileServicerMockRecorder) UpdateProfile(ctx, id, input any) *MockProfileServicerUpdateProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileServicer)(nil).UpdateProfile), ctx, id, input)
	return &MockProfileServicerUpdateProfileCall{Call: call}
}

// MockProfileServicerUpdateProfileCall wrap *gomock.Call
type MockProfileServicerUpdateProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProfileServicerUpdateProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockProfileServicerUpdateProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProfileServicerUpdateProfileCall) Do(f func(context.Context, string, db.UpdateProfileInput) (*db.ScanProfile, error)) *MockProfileServicerUpdateProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProfileServicerUpdateProfileCall) DoAndReturn(f func(context.Context, string, db.UpdateProfileInput) (*db.ScanProfile, error)) *MockProfileServicerUpdateProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
