// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: ScheduleStore)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_schedule_store.go -package mocks github.com/anstrom/scanorama/internal/api/handlers ScheduleStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleStore is a mock of ScheduleStore interface.
type MockScheduleStore struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleStoreMockRecorder
	isgomock struct{}
}

// MockScheduleStoreMockRecorder is the mock recorder for MockScheduleStore.
type MockScheduleStoreMockRecorder struct {
	mock *MockScheduleStore
}

// NewMockScheduleStore creates a new mock instance.
func NewMockScheduleStore(ctrl *gomock.Controller) *MockScheduleStore {
	mock := &MockScheduleStore{ctrl: ctrl}
	mock.recorder = &MockScheduleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleStore) EXPECT() *MockScheduleStoreMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockScheduleStore) CreateSchedule(ctx context.Context, input db.CreateScheduleInput) (*db.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, input)
	ret0, _ := ret[0].(*db.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleStoreMockRecorder) CreateSchedule(ctx, input any) *MockScheduleStoreCreateScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleStore)(nil).CreateSchedule), ctx, input)
	return &MockScheduleStoreCreateScheduleCall{Call: call}
}

// MockScheduleStoreCreateScheduleCall wrap *gomock.Call
type MockScheduleStoreCreateScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleStoreCreateScheduleCall) Return(arg0 *db.Schedule, arg1 error) *MockScheduleStoreCreateScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleStoreCreateScheduleCall) Do(f func(context.Context, db.CreateScheduleInput) (*db.Schedule, error)) *MockScheduleStoreCreateScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleStoreCreateScheduleCall) DoAndReturn(f func(context.Context, db.CreateScheduleInput) (*db.Schedule, error)) *MockScheduleStoreCreateScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteSchedule mocks base method.
func (m *MockScheduleStore) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockScheduleStoreMockRecorder) DeleteSchedule(ctx, id any) *MockScheduleStoreDeleteScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockScheduleStore)(nil).DeleteSchedule), ctx, id)
	return &MockScheduleStoreDeleteScheduleCall{Call: call}
}

// MockScheduleStoreDeleteScheduleCall wrap *gomock.Call
type MockScheduleStoreDeleteScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleStoreDeleteScheduleCall) Return(arg0 error) *MockScheduleStoreDeleteScheduleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleStoreDeleteScheduleCall) Do(f func(context.Context, uuid.UUID) error) *MockScheduleStoreDeleteScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleStoreDeleteScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScheduleStoreDeleteScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DisableSchedule mocks base method.
func (m *MockScheduleStore) DisableSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableSchedule indicates an expected call of DisableSchedule.
func (mr *MockScheduleStoreMockRecorder) DisableSchedule(ctx, id any) *MockScheduleStoreDisableScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableSchedule", reflect.TypeOf((*MockScheduleStore)(nil).DisableSchedule), ctx, id)
	return &MockScheduleStoreDisableScheduleCall{Call: call}
}

// MockScheduleStoreDisableScheduleCall wrap *gomock.Call
type MockScheduleStoreDisableScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleStoreDisableScheduleCall) Return(arg0 error) *MockScheduleStoreDisableScheduleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleStoreDisableScheduleCall) Do(f func(context.Context, uuid.UUID) error) *MockScheduleStoreDisableScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleStoreDisableScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScheduleStoreDisableScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EnableSchedule mocks base method.
func (m *MockScheduleStore) EnableSchedule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableSchedule indicates an expected call of EnableSchedule.
func (mr *MockScheduleStoreMockRecorder) EnableSchedule(ctx, id any) *MockScheduleStoreEnableScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableSchedule", reflect.TypeOf((*MockScheduleStore)(nil).EnableSchedule), ctx, id)
	return &MockScheduleStoreEnableScheduleCall{Call: call}
}

// MockScheduleStoreEnableScheduleCall wrap *gomock.Call
type MockScheduleStoreEnableScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleStoreEnableScheduleCall) Return(arg0 error) *MockScheduleStoreEnableScheduleCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleStoreEnableScheduleCall) Do(f func(context.Context, uuid.UUID) error) *MockScheduleStoreEnableScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleStoreEnableScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScheduleStoreEnableScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetSchedule mocks base method.
func (m *MockScheduleStore) GetSchedule(ctx context.Context, id uuid.UUID) (*db.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchedule", ctx, id)
	ret0, _ := ret[0].(*db.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSchedule indicates an expected call of GetSchedule.
func (mr *MockScheduleStoreMockRecorder) GetSchedule(ctx, id any) *MockScheduleStoreGetScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchedule", reflect.TypeOf((*MockScheduleStore)(nil).GetSchedule), ctx, id)
	return &MockScheduleStoreGetScheduleCall{Call: call}
}

// MockScheduleStoreGetScheduleCall wrap *gomock.Call
type MockScheduleStoreGetScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleStoreGetScheduleCall) Return(arg0 *db.Schedule, arg1 error) *MockScheduleStoreGetScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleStoreGetScheduleCall) Do(f func(context.Context, uuid.UUID) (*db.Schedule, error)) *MockScheduleStoreGetScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleStoreGetScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.Schedule, error)) *MockScheduleStoreGetScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSchedules mocks base method.
func (m *MockScheduleStore) ListSchedules(ctx context.Context, filters db.ScheduleFilters, offset, limit int) ([]*db.Schedule, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.Schedule)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockScheduleStoreMockRecorder) ListSchedules(ctx, filters, offset, limit any) *MockScheduleStoreListSchedulesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockScheduleStore)(nil).ListSchedules), ctx, filters, offset, limit)
	return &MockScheduleStoreListSchedulesCall{Call: call}
}

// MockScheduleStoreListSchedulesCall wrap *gomock.Call
type MockScheduleStoreListSchedulesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleStoreListSchedulesCall) Return(arg0 []*db.Schedule, arg1 int64, arg2 error) *MockScheduleStoreListSchedulesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleStoreListSchedulesCall) Do(f func(context.Context, db.ScheduleFilters, int, int) ([]*db.Schedule, int64, error)) *MockScheduleStoreListSchedulesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleStoreListSchedulesCall) DoAndReturn(f func(context.Context, db.ScheduleFilters, int, int) ([]*db.Schedule, int64, error)) *MockScheduleStoreListSchedulesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateSchedule mocks base method.
func (m *MockScheduleStore) UpdateSchedule(ctx context.Context, id uuid.UUID, input db.UpdateScheduleInput) (*db.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSchedule", ctx, id, input)
	ret0, _ := ret[0].(*db.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSchedule indicates an expected call of UpdateSchedule.
func (mr *MockScheduleStoreMockRecorder) UpdateSchedule(ctx, id, input any) *MockScheduleStoreUpdateScheduleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSchedule", reflect.TypeOf((*MockScheduleStore)(nil).UpdateSchedule), ctx, id, input)
	return &MockScheduleStoreUpdateScheduleCall{Call: call}
}

// MockScheduleStoreUpdateScheduleCall wrap *gomock.Call
type MockScheduleStoreUpdateScheduleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScheduleStoreUpdateScheduleCall) Return(arg0 *db.Schedule, arg1 error) *MockScheduleStoreUpdateScheduleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScheduleStoreUpdateScheduleCall) Do(f func(context.Context, uuid.UUID, db.UpdateScheduleInput) (*db.Schedule, error)) *MockScheduleStoreUpdateScheduleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScheduleStoreUpdateScheduleCall) DoAndReturn(f func(context.Context, uuid.UUID, db.UpdateScheduleInput) (*db.Schedule, error)) *MockScheduleStoreUpdateScheduleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
