// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: ScanStore)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_scan_store.go -package mocks github.com/anstrom/scanorama/internal/api/handlers ScanStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockScanStore is a mock of ScanStore interface.
type MockScanStore struct {
	ctrl     *gomock.Controller
	recorder *MockScanStoreMockRecorder
	isgomock struct{}
}

// MockScanStoreMockRecorder is the mock recorder for MockScanStore.
type MockScanStoreMockRecorder struct {
	mock *MockScanStore
}

// NewMockScanStore creates a new mock instance.
func NewMockScanStore(ctrl *gomock.Controller) *MockScanStore {
	mock := &MockScanStore{ctrl: ctrl}
	mock.recorder = &MockScanStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanStore) EXPECT() *MockScanStoreMockRecorder {
	return m.recorder
}

// CompleteScan mocks base method.
func (m *MockScanStore) CompleteScan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteScan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteScan indicates an expected call of CompleteScan.
func (mr *MockScanStoreMockRecorder) CompleteScan(ctx, id any) *MockScanStoreCompleteScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteScan", reflect.TypeOf((*MockScanStore)(nil).CompleteScan), ctx, id)
	return &MockScanStoreCompleteScanCall{Call: call}
}

// MockScanStoreCompleteScanCall wrap *gomock.Call
type MockScanStoreCompleteScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreCompleteScanCall) Return(arg0 error) *MockScanStoreCompleteScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreCompleteScanCall) Do(f func(context.Context, uuid.UUID) error) *MockScanStoreCompleteScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreCompleteScanCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScanStoreCompleteScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateScan mocks base method.
func (m *MockScanStore) CreateScan(ctx context.Context, input any) (*db.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScan", ctx, input)
	ret0, _ := ret[0].(*db.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScan indicates an expected call of CreateScan.
func (mr *MockScanStoreMockRecorder) CreateScan(ctx, input any) *MockScanStoreCreateScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScan", reflect.TypeOf((*MockScanStore)(nil).CreateScan), ctx, input)
	return &MockScanStoreCreateScanCall{Call: call}
}

// MockScanStoreCreateScanCall wrap *gomock.Call
type MockScanStoreCreateScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreCreateScanCall) Return(arg0 *db.Scan, arg1 error) *MockScanStoreCreateScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreCreateScanCall) Do(f func(context.Context, any) (*db.Scan, error)) *MockScanStoreCreateScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreCreateScanCall) DoAndReturn(f func(context.Context, any) (*db.Scan, error)) *MockScanStoreCreateScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteScan mocks base method.
func (m *MockScanStore) DeleteScan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScan indicates an expected call of DeleteScan.
func (mr *MockScanStoreMockRecorder) DeleteScan(ctx, id any) *MockScanStoreDeleteScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScan", reflect.TypeOf((*MockScanStore)(nil).DeleteScan), ctx, id)
	return &MockScanStoreDeleteScanCall{Call: call}
}

// MockScanStoreDeleteScanCall wrap *gomock.Call
type MockScanStoreDeleteScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreDeleteScanCall) Return(arg0 error) *MockScanStoreDeleteScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreDeleteScanCall) Do(f func(context.Context, uuid.UUID) error) *MockScanStoreDeleteScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreDeleteScanCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScanStoreDeleteScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetScan mocks base method.
func (m *MockScanStore) GetScan(ctx context.Context, id uuid.UUID) (*db.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScan", ctx, id)
	ret0, _ := ret[0].(*db.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScan indicates an expected call of GetScan.
func (mr *MockScanStoreMockRecorder) GetScan(ctx, id any) *MockScanStoreGetScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScan", reflect.TypeOf((*MockScanStore)(nil).GetScan), ctx, id)
	return &MockScanStoreGetScanCall{Call: call}
}

// MockScanStoreGetScanCall wrap *gomock.Call
type MockScanStoreGetScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreGetScanCall) Return(arg0 *db.Scan, arg1 error) *MockScanStoreGetScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreGetScanCall) Do(f func(context.Context, uuid.UUID) (*db.Scan, error)) *MockScanStoreGetScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreGetScanCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.Scan, error)) *MockScanStoreGetScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetScanResults mocks base method.
func (m *MockScanStore) GetScanResults(ctx context.Context, scanID uuid.UUID, offset, limit int) ([]*db.ScanResult, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanResults", ctx, scanID, offset, limit)
	ret0, _ := ret[0].([]*db.ScanResult)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetScanResults indicates an expected call of GetScanResults.
func (mr *MockScanStoreMockRecorder) GetScanResults(ctx, scanID, offset, limit any) *MockScanStoreGetScanResultsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanResults", reflect.TypeOf((*MockScanStore)(nil).GetScanResults), ctx, scanID, offset, limit)
	return &MockScanStoreGetScanResultsCall{Call: call}
}

// MockScanStoreGetScanResultsCall wrap *gomock.Call
type MockScanStoreGetScanResultsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreGetScanResultsCall) Return(arg0 []*db.ScanResult, arg1 int64, arg2 error) *MockScanStoreGetScanResultsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreGetScanResultsCall) Do(f func(context.Context, uuid.UUID, int, int) ([]*db.ScanResult, int64, error)) *MockScanStoreGetScanResultsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreGetScanResultsCall) DoAndReturn(f func(context.Context, uuid.UUID, int, int) ([]*db.ScanResult, int64, error)) *MockScanStoreGetScanResultsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetScanSummary mocks base method.
func (m *MockScanStore) GetScanSummary(ctx context.Context, scanID uuid.UUID) (*db.ScanSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanSummary", ctx, scanID)
	ret0, _ := ret[0].(*db.ScanSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScanSummary indicates an expected call of GetScanSummary.
func (mr *MockScanStoreMockRecorder) GetScanSummary(ctx, scanID any) *MockScanStoreGetScanSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanSummary", reflect.TypeOf((*MockScanStore)(nil).GetScanSummary), ctx, scanID)
	return &MockScanStoreGetScanSummaryCall{Call: call}
}

// MockScanStoreGetScanSummaryCall wrap *gomock.Call
type MockScanStoreGetScanSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreGetScanSummaryCall) Return(arg0 *db.ScanSummary, arg1 error) *MockScanStoreGetScanSummaryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreGetScanSummaryCall) Do(f func(context.Context, uuid.UUID) (*db.ScanSummary, error)) *MockScanStoreGetScanSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreGetScanSummaryCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.ScanSummary, error)) *MockScanStoreGetScanSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListScans mocks base method.
func (m *MockScanStore) ListScans(ctx context.Context, filters db.ScanFilters, offset, limit int) ([]*db.Scan, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScans", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.Scan)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListScans indicates an expected call of ListScans.
func (mr *MockScanStoreMockRecorder) ListScans(ctx, filters, offset, limit any) *MockScanStoreListScansCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScans", reflect.TypeOf((*MockScanStore)(nil).ListScans), ctx, filters, offset, limit)
	return &MockScanStoreListScansCall{Call: call}
}

// MockScanStoreListScansCall wrap *gomock.Call
type MockScanStoreListScansCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreListScansCall) Return(arg0 []*db.Scan, arg1 int64, arg2 error) *MockScanStoreListScansCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreListScansCall) Do(f func(context.Context, db.ScanFilters, int, int) ([]*db.Scan, int64, error)) *MockScanStoreListScansCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreListScansCall) DoAndReturn(f func(context.Context, db.ScanFilters, int, int) ([]*db.Scan, int64, error)) *MockScanStoreListScansCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartScan mocks base method.
func (m *MockScanStore) StartScan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartScan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartScan indicates an expected call of StartScan.
func (mr *MockScanStoreMockRecorder) StartScan(ctx, id any) *MockScanStoreStartScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartScan", reflect.TypeOf((*MockScanStore)(nil).StartScan), ctx, id)
	return &MockScanStoreStartScanCall{Call: call}
}

// MockScanStoreStartScanCall wrap *gomock.Call
type MockScanStoreStartScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreStartScanCall) Return(arg0 error) *MockScanStoreStartScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreStartScanCall) Do(f func(context.Context, uuid.UUID) error) *MockScanStoreStartScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreStartScanCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScanStoreStartScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopScan mocks base method.
func (m *MockScanStore) StopScan(ctx context.Context, id uuid.UUID, errMsg ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range errMsg {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopScan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopScan indicates an expected call of StopScan.
func (mr *MockScanStoreMockRecorder) StopScan(ctx, id any, errMsg ...any) *MockScanStoreStopScanCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, errMsg...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopScan", reflect.TypeOf((*MockScanStore)(nil).StopScan), varargs...)
	return &MockScanStoreStopScanCall{Call: call}
}

// MockScanStoreStopScanCall wrap *gomock.Call
type MockScanStoreStopScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreStopScanCall) Return(arg0 error) *MockScanStoreStopScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreStopScanCall) Do(f func(context.Context, uuid.UUID, ...string) error) *MockScanStoreStopScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreStopScanCall) DoAndReturn(f func(context.Context, uuid.UUID, ...string) error) *MockScanStoreStopScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateScan mocks base method.
func (m *MockScanStore) UpdateScan(ctx context.Context, id uuid.UUID, scanData any) (*db.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScan", ctx, id, scanData)
	ret0, _ := ret[0].(*db.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScan indicates an expected call of UpdateScan.
func (mr *MockScanStoreMockRecorder) UpdateScan(ctx, id, scanData any) *MockScanStoreUpdateScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScan", reflect.TypeOf((*MockScanStore)(nil).UpdateScan), ctx, id, scanData)
	return &MockScanStoreUpdateScanCall{Call: call}
}

// MockScanStoreUpdateScanCall wrap *gomock.Call
type MockScanStoreUpdateScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanStoreUpdateScanCall) Return(arg0 *db.Scan, arg1 error) *MockScanStoreUpdateScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanStoreUpdateScanCall) Do(f func(context.Context, uuid.UUID, any) (*db.Scan, error)) *MockScanStoreUpdateScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanStoreUpdateScanCall) DoAndReturn(f func(context.Context, uuid.UUID, any) (*db.Scan, error)) *MockScanStoreUpdateScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
