// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: GroupServicer)
//
// Generated by this command:
//
//	mockgen -typed -destination internal/api/handlers/mocks/mock_group_servicer.go -package mocks github.com/anstrom/scanorama/internal/api/handlers GroupServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupServicer is a mock of GroupServicer interface.
type MockGroupServicer struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServicerMockRecorder
	isgomock struct{}
}

// MockGroupServicerMockRecorder is the mock recorder for MockGroupServicer.
type MockGroupServicerMockRecorder struct {
	mock *MockGroupServicer
}

// NewMockGroupServicer creates a new mock instance.
func NewMockGroupServicer(ctrl *gomock.Controller) *MockGroupServicer {
	mock := &MockGroupServicer{ctrl: ctrl}
	mock.recorder = &MockGroupServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupServicer) EXPECT() *MockGroupServicerMockRecorder {
	return m.recorder
}

// AddHostsToGroup mocks base method.
func (m *MockGroupServicer) AddHostsToGroup(ctx context.Context, groupID uuid.UUID, hostIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHostsToGroup", ctx, groupID, hostIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddHostsToGroup indicates an expected call of AddHostsToGroup.
func (mr *MockGroupServicerMockRecorder) AddHostsToGroup(ctx, groupID, hostIDs any) *MockGroupServicerAddHostsToGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHostsToGroup", reflect.TypeOf((*MockGroupServicer)(nil).AddHostsToGroup), ctx, groupID, hostIDs)
	return &MockGroupServicerAddHostsToGroupCall{Call: call}
}

// MockGroupServicerAddHostsToGroupCall wrap *gomock.Call
type MockGroupServicerAddHostsToGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerAddHostsToGroupCall) Return(arg0 error) *MockGroupServicerAddHostsToGroupCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerAddHostsToGroupCall) Do(f func(context.Context, uuid.UUID, []uuid.UUID) error) *MockGroupServicerAddHostsToGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerAddHostsToGroupCall) DoAndReturn(f func(context.Context, uuid.UUID, []uuid.UUID) error) *MockGroupServicerAddHostsToGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateGroup mocks base method.
func (m *MockGroupServicer) CreateGroup(ctx context.Context, input db.CreateGroupInput) (*db.HostGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, input)
	ret0, _ := ret[0].(*db.HostGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupServicerMockRecorder) CreateGroup(ctx, input any) *MockGroupServicerCreateGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupServicer)(nil).CreateGroup), ctx, input)
	return &MockGroupServicerCreateGroupCall{Call: call}
}

// MockGroupServicerCreateGroupCall wrap *gomock.Call
type MockGroupServicerCreateGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerCreateGroupCall) Return(arg0 *db.HostGroup, arg1 error) *MockGroupServicerCreateGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerCreateGroupCall) Do(f func(context.Context, db.CreateGroupInput) (*db.HostGroup, error)) *MockGroupServicerCreateGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerCreateGroupCall) DoAndReturn(f func(context.Context, db.CreateGroupInput) (*db.HostGroup, error)) *MockGroupServicerCreateGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteGroup mocks base method.
func (m *MockGroupServicer) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupServicerMockRecorder) DeleteGroup(ctx, id any) *MockGroupServicerDeleteGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupServicer)(nil).DeleteGroup), ctx, id)
	return &MockGroupServicerDeleteGroupCall{Call: call}
}

// MockGroupServicerDeleteGroupCall wrap *gomock.Call
type MockGroupServicerDeleteGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerDeleteGroupCall) Return(arg0 error) *MockGroupServicerDeleteGroupCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerDeleteGroupCall) Do(f func(context.Context, uuid.UUID) error) *MockGroupServicerDeleteGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerDeleteGroupCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockGroupServicerDeleteGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGroup mocks base method.
func (m *MockGroupServicer) GetGroup(ctx context.Context, id uuid.UUID) (*db.HostGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", ctx, id)
	ret0, _ := ret[0].(*db.HostGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockGroupServicerMockRecorder) GetGroup(ctx, id any) *MockGroupServicerGetGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockGroupServicer)(nil).GetGroup), ctx, id)
	return &MockGroupServicerGetGroupCall{Call: call}
}

// MockGroupServicerGetGroupCall wrap *gomock.Call
type MockGroupServicerGetGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerGetGroupCall) Return(arg0 *db.HostGroup, arg1 error) *MockGroupServicerGetGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerGetGroupCall) Do(f func(context.Context, uuid.UUID) (*db.HostGroup, error)) *MockGroupServicerGetGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerGetGroupCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.HostGroup, error)) *MockGroupServicerGetGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGroupMembers mocks base method.
func (m *MockGroupServicer) GetGroupMembers(ctx context.Context, groupID uuid.UUID, offset, limit int) ([]*db.Host, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMembers", ctx, groupID, offset, limit)
	ret0, _ := ret[0].([]*db.Host)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGroupMembers indicates an expected call of GetGroupMembers.
func (mr *MockGroupServicerMockRecorder) GetGroupMembers(ctx, groupID, offset, limit any) *MockGroupServicerGetGroupMembersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMembers", reflect.TypeOf((*MockGroupServicer)(nil).GetGroupMembers), ctx, groupID, offset, limit)
	return &MockGroupServicerGetGroupMembersCall{Call: call}
}

// MockGroupServicerGetGroupMembersCall wrap *gomock.Call
type MockGroupServicerGetGroupMembersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerGetGroupMembersCall) Return(arg0 []*db.Host, arg1 int64, arg2 error) *MockGroupServicerGetGroupMembersCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerGetGroupMembersCall) Do(f func(context.Context, uuid.UUID, int, int) ([]*db.Host, int64, error)) *MockGroupServicerGetGroupMembersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerGetGroupMembersCall) DoAndReturn(f func(context.Context, uuid.UUID, int, int) ([]*db.Host, int64, error)) *MockGroupServicerGetGroupMembersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListGroups mocks base method.
func (m *MockGroupServicer) ListGroups(ctx context.Context) ([]*db.HostGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx)
	ret0, _ := ret[0].([]*db.HostGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupServicerMockRecorder) ListGroups(ctx any) *MockGroupServicerListGroupsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupServicer)(nil).ListGroups), ctx)
	return &MockGroupServicerListGroupsCall{Call: call}
}

// MockGroupServicerListGroupsCall wrap *gomock.Call
type MockGroupServicerListGroupsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerListGroupsCall) Return(arg0 []*db.HostGroup, arg1 error) *MockGroupServicerListGroupsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerListGroupsCall) Do(f func(context.Context) ([]*db.HostGroup, error)) *MockGroupServicerListGroupsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerListGroupsCall) DoAndReturn(f func(context.Context) ([]*db.HostGroup, error)) *MockGroupServicerListGroupsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveHostsFromGroup mocks base method.
func (m *MockGroupServicer) RemoveHostsFromGroup(ctx context.Context, groupID uuid.UUID, hostIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHostsFromGroup", ctx, groupID, hostIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHostsFromGroup indicates an expected call of RemoveHostsFromGroup.
func (mr *MockGroupServicerMockRecorder) RemoveHostsFromGroup(ctx, groupID, hostIDs any) *MockGroupServicerRemoveHostsFromGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHostsFromGroup", reflect.TypeOf((*MockGroupServicer)(nil).RemoveHostsFromGroup), ctx, groupID, hostIDs)
	return &MockGroupServicerRemoveHostsFromGroupCall{Call: call}
}

// MockGroupServicerRemoveHostsFromGroupCall wrap *gomock.Call
type MockGroupServicerRemoveHostsFromGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerRemoveHostsFromGroupCall) Return(arg0 error) *MockGroupServicerRemoveHostsFromGroupCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerRemoveHostsFromGroupCall) Do(f func(context.Context, uuid.UUID, []uuid.UUID) error) *MockGroupServicerRemoveHostsFromGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerRemoveHostsFromGroupCall) DoAndReturn(f func(context.Context, uuid.UUID, []uuid.UUID) error) *MockGroupServicerRemoveHostsFromGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateGroup mocks base method.
func (m *MockGroupServicer) UpdateGroup(ctx context.Context, id uuid.UUID, input db.UpdateGroupInput) (*db.HostGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, id, input)
	ret0, _ := ret[0].(*db.HostGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupServicerMockRecorder) UpdateGroup(ctx, id, input any) *MockGroupServicerUpdateGroupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupServicer)(nil).UpdateGroup), ctx, id, input)
	return &MockGroupServicerUpdateGroupCall{Call: call}
}

// MockGroupServicerUpdateGroupCall wrap *gomock.Call
type MockGroupServicerUpdateGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGroupServicerUpdateGroupCall) Return(arg0 *db.HostGroup, arg1 error) *MockGroupServicerUpdateGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGroupServicerUpdateGroupCall) Do(f func(context.Context, uuid.UUID, db.UpdateGroupInput) (*db.HostGroup, error)) *MockGroupServicerUpdateGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGroupServicerUpdateGroupCall) DoAndReturn(f func(context.Context, uuid.UUID, db.UpdateGroupInput) (*db.HostGroup, error)) *MockGroupServicerUpdateGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
