// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: DiscoveryStore)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_discovery_store.go -package mocks github.com/anstrom/scanorama/internal/api/handlers DiscoveryStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDiscoveryStore is a mock of DiscoveryStore interface.
type MockDiscoveryStore struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryStoreMockRecorder
	isgomock struct{}
}

// MockDiscoveryStoreMockRecorder is the mock recorder for MockDiscoveryStore.
type MockDiscoveryStoreMockRecorder struct {
	mock *MockDiscoveryStore
}

// NewMockDiscoveryStore creates a new mock instance.
func NewMockDiscoveryStore(ctrl *gomock.Controller) *MockDiscoveryStore {
	mock := &MockDiscoveryStore{ctrl: ctrl}
	mock.recorder = &MockDiscoveryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoveryStore) EXPECT() *MockDiscoveryStoreMockRecorder {
	return m.recorder
}

// CreateDiscoveryJob mocks base method.
func (m *MockDiscoveryStore) CreateDiscoveryJob(ctx context.Context, input db.CreateDiscoveryJobInput) (*db.DiscoveryJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiscoveryJob", ctx, input)
	ret0, _ := ret[0].(*db.DiscoveryJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDiscoveryJob indicates an expected call of CreateDiscoveryJob.
func (mr *MockDiscoveryStoreMockRecorder) CreateDiscoveryJob(ctx, input any) *MockDiscoveryStoreCreateDiscoveryJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiscoveryJob", reflect.TypeOf((*MockDiscoveryStore)(nil).CreateDiscoveryJob), ctx, input)
	return &MockDiscoveryStoreCreateDiscoveryJobCall{Call: call}
}

// MockDiscoveryStoreCreateDiscoveryJobCall wrap *gomock.Call
type MockDiscoveryStoreCreateDiscoveryJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreCreateDiscoveryJobCall) Return(arg0 *db.DiscoveryJob, arg1 error) *MockDiscoveryStoreCreateDiscoveryJobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreCreateDiscoveryJobCall) Do(f func(context.Context, db.CreateDiscoveryJobInput) (*db.DiscoveryJob, error)) *MockDiscoveryStoreCreateDiscoveryJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreCreateDiscoveryJobCall) DoAndReturn(f func(context.Context, db.CreateDiscoveryJobInput) (*db.DiscoveryJob, error)) *MockDiscoveryStoreCreateDiscoveryJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteDiscoveryJob mocks base method.
func (m *MockDiscoveryStore) DeleteDiscoveryJob(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscoveryJob", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscoveryJob indicates an expected call of DeleteDiscoveryJob.
func (mr *MockDiscoveryStoreMockRecorder) DeleteDiscoveryJob(ctx, id any) *MockDiscoveryStoreDeleteDiscoveryJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscoveryJob", reflect.TypeOf((*MockDiscoveryStore)(nil).DeleteDiscoveryJob), ctx, id)
	return &MockDiscoveryStoreDeleteDiscoveryJobCall{Call: call}
}

// MockDiscoveryStoreDeleteDiscoveryJobCall wrap *gomock.Call
type MockDiscoveryStoreDeleteDiscoveryJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreDeleteDiscoveryJobCall) Return(arg0 error) *MockDiscoveryStoreDeleteDiscoveryJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreDeleteDiscoveryJobCall) Do(f func(context.Context, uuid.UUID) error) *MockDiscoveryStoreDeleteDiscoveryJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreDeleteDiscoveryJobCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockDiscoveryStoreDeleteDiscoveryJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDiscoveryJob mocks base method.
func (m *MockDiscoveryStore) GetDiscoveryJob(ctx context.Context, id uuid.UUID) (*db.DiscoveryJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscoveryJob", ctx, id)
	ret0, _ := ret[0].(*db.DiscoveryJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscoveryJob indicates an expected call of GetDiscoveryJob.
func (mr *MockDiscoveryStoreMockRecorder) GetDiscoveryJob(ctx, id any) *MockDiscoveryStoreGetDiscoveryJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscoveryJob", reflect.TypeOf((*MockDiscoveryStore)(nil).GetDiscoveryJob), ctx, id)
	return &MockDiscoveryStoreGetDiscoveryJobCall{Call: call}
}

// MockDiscoveryStoreGetDiscoveryJobCall wrap *gomock.Call
type MockDiscoveryStoreGetDiscoveryJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreGetDiscoveryJobCall) Return(arg0 *db.DiscoveryJob, arg1 error) *MockDiscoveryStoreGetDiscoveryJobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreGetDiscoveryJobCall) Do(f func(context.Context, uuid.UUID) (*db.DiscoveryJob, error)) *MockDiscoveryStoreGetDiscoveryJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreGetDiscoveryJobCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.DiscoveryJob, error)) *MockDiscoveryStoreGetDiscoveryJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDiscoveryJobs mocks base method.
func (m *MockDiscoveryStore) ListDiscoveryJobs(ctx context.Context, filters db.DiscoveryFilters, offset, limit int) ([]*db.DiscoveryJob, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscoveryJobs", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.DiscoveryJob)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDiscoveryJobs indicates an expected call of ListDiscoveryJobs.
func (mr *MockDiscoveryStoreMockRecorder) ListDiscoveryJobs(ctx, filters, offset, limit any) *MockDiscoveryStoreListDiscoveryJobsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscoveryJobs", reflect.TypeOf((*MockDiscoveryStore)(nil).ListDiscoveryJobs), ctx, filters, offset, limit)
	return &MockDiscoveryStoreListDiscoveryJobsCall{Call: call}
}

// MockDiscoveryStoreListDiscoveryJobsCall wrap *gomock.Call
type MockDiscoveryStoreListDiscoveryJobsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreListDiscoveryJobsCall) Return(arg0 []*db.DiscoveryJob, arg1 int64, arg2 error) *MockDiscoveryStoreListDiscoveryJobsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreListDiscoveryJobsCall) Do(f func(context.Context, db.DiscoveryFilters, int, int) ([]*db.DiscoveryJob, int64, error)) *MockDiscoveryStoreListDiscoveryJobsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreListDiscoveryJobsCall) DoAndReturn(f func(context.Context, db.DiscoveryFilters, int, int) ([]*db.DiscoveryJob, int64, error)) *MockDiscoveryStoreListDiscoveryJobsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListDiscoveryJobsByNetwork mocks base method.
func (m *MockDiscoveryStore) ListDiscoveryJobsByNetwork(ctx context.Context, networkID uuid.UUID, offset, limit int) ([]*db.DiscoveryJob, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscoveryJobsByNetwork", ctx, networkID, offset, limit)
	ret0, _ := ret[0].([]*db.DiscoveryJob)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDiscoveryJobsByNetwork indicates an expected call of ListDiscoveryJobsByNetwork.
func (mr *MockDiscoveryStoreMockRecorder) ListDiscoveryJobsByNetwork(ctx, networkID, offset, limit any) *MockDiscoveryStoreListDiscoveryJobsByNetworkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscoveryJobsByNetwork", reflect.TypeOf((*MockDiscoveryStore)(nil).ListDiscoveryJobsByNetwork), ctx, networkID, offset, limit)
	return &MockDiscoveryStoreListDiscoveryJobsByNetworkCall{Call: call}
}

// MockDiscoveryStoreListDiscoveryJobsByNetworkCall wrap *gomock.Call
type MockDiscoveryStoreListDiscoveryJobsByNetworkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreListDiscoveryJobsByNetworkCall) Return(arg0 []*db.DiscoveryJob, arg1 int64, arg2 error) *MockDiscoveryStoreListDiscoveryJobsByNetworkCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreListDiscoveryJobsByNetworkCall) Do(f func(context.Context, uuid.UUID, int, int) ([]*db.DiscoveryJob, int64, error)) *MockDiscoveryStoreListDiscoveryJobsByNetworkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreListDiscoveryJobsByNetworkCall) DoAndReturn(f func(context.Context, uuid.UUID, int, int) ([]*db.DiscoveryJob, int64, error)) *MockDiscoveryStoreListDiscoveryJobsByNetworkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartDiscoveryJob mocks base method.
func (m *MockDiscoveryStore) StartDiscoveryJob(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDiscoveryJob", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartDiscoveryJob indicates an expected call of StartDiscoveryJob.
func (mr *MockDiscoveryStoreMockRecorder) StartDiscoveryJob(ctx, id any) *MockDiscoveryStoreStartDiscoveryJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDiscoveryJob", reflect.TypeOf((*MockDiscoveryStore)(nil).StartDiscoveryJob), ctx, id)
	return &MockDiscoveryStoreStartDiscoveryJobCall{Call: call}
}

// MockDiscoveryStoreStartDiscoveryJobCall wrap *gomock.Call
type MockDiscoveryStoreStartDiscoveryJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreStartDiscoveryJobCall) Return(arg0 error) *MockDiscoveryStoreStartDiscoveryJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreStartDiscoveryJobCall) Do(f func(context.Context, uuid.UUID) error) *MockDiscoveryStoreStartDiscoveryJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreStartDiscoveryJobCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockDiscoveryStoreStartDiscoveryJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopDiscoveryJob mocks base method.
func (m *MockDiscoveryStore) StopDiscoveryJob(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopDiscoveryJob", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopDiscoveryJob indicates an expected call of StopDiscoveryJob.
func (mr *MockDiscoveryStoreMockRecorder) StopDiscoveryJob(ctx, id any) *MockDiscoveryStoreStopDiscoveryJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDiscoveryJob", reflect.TypeOf((*MockDiscoveryStore)(nil).StopDiscoveryJob), ctx, id)
	return &MockDiscoveryStoreStopDiscoveryJobCall{Call: call}
}

// MockDiscoveryStoreStopDiscoveryJobCall wrap *gomock.Call
type MockDiscoveryStoreStopDiscoveryJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreStopDiscoveryJobCall) Return(arg0 error) *MockDiscoveryStoreStopDiscoveryJobCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreStopDiscoveryJobCall) Do(f func(context.Context, uuid.UUID) error) *MockDiscoveryStoreStopDiscoveryJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreStopDiscoveryJobCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockDiscoveryStoreStopDiscoveryJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDiscoveryJob mocks base method.
func (m *MockDiscoveryStore) UpdateDiscoveryJob(ctx context.Context, id uuid.UUID, input db.UpdateDiscoveryJobInput) (*db.DiscoveryJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDiscoveryJob", ctx, id, input)
	ret0, _ := ret[0].(*db.DiscoveryJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDiscoveryJob indicates an expected call of UpdateDiscoveryJob.
func (mr *MockDiscoveryStoreMockRecorder) UpdateDiscoveryJob(ctx, id, input any) *MockDiscoveryStoreUpdateDiscoveryJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDiscoveryJob", reflect.TypeOf((*MockDiscoveryStore)(nil).UpdateDiscoveryJob), ctx, id, input)
	return &MockDiscoveryStoreUpdateDiscoveryJobCall{Call: call}
}

// MockDiscoveryStoreUpdateDiscoveryJobCall wrap *gomock.Call
type MockDiscoveryStoreUpdateDiscoveryJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiscoveryStoreUpdateDiscoveryJobCall) Return(arg0 *db.DiscoveryJob, arg1 error) *MockDiscoveryStoreUpdateDiscoveryJobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiscoveryStoreUpdateDiscoveryJobCall) Do(f func(context.Context, uuid.UUID, db.UpdateDiscoveryJobInput) (*db.DiscoveryJob, error)) *MockDiscoveryStoreUpdateDiscoveryJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiscoveryStoreUpdateDiscoveryJobCall) DoAndReturn(f func(context.Context, uuid.UUID, db.UpdateDiscoveryJobInput) (*db.DiscoveryJob, error)) *MockDiscoveryStoreUpdateDiscoveryJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
