// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: ScanServicer)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_scan_servicer.go -package mocks github.com/anstrom/scanorama/internal/api/handlers ScanServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockScanServicer is a mock of ScanServicer interface.
type MockScanServicer struct {
	ctrl     *gomock.Controller
	recorder *MockScanServicerMockRecorder
	isgomock struct{}
}

// MockScanServicerMockRecorder is the mock recorder for MockScanServicer.
type MockScanServicerMockRecorder struct {
	mock *MockScanServicer
}

// NewMockScanServicer creates a new mock instance.
func NewMockScanServicer(ctrl *gomock.Controller) *MockScanServicer {
	mock := &MockScanServicer{ctrl: ctrl}
	mock.recorder = &MockScanServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScanServicer) EXPECT() *MockScanServicerMockRecorder {
	return m.recorder
}

// CompleteScan mocks base method.
func (m *MockScanServicer) CompleteScan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteScan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteScan indicates an expected call of CompleteScan.
func (mr *MockScanServicerMockRecorder) CompleteScan(ctx, id any) *MockScanServicerCompleteScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteScan", reflect.TypeOf((*MockScanServicer)(nil).CompleteScan), ctx, id)
	return &MockScanServicerCompleteScanCall{Call: call}
}

// MockScanServicerCompleteScanCall wrap *gomock.Call
type MockScanServicerCompleteScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerCompleteScanCall) Return(arg0 error) *MockScanServicerCompleteScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerCompleteScanCall) Do(f func(context.Context, uuid.UUID) error) *MockScanServicerCompleteScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerCompleteScanCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScanServicerCompleteScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateScan mocks base method.
func (m *MockScanServicer) CreateScan(ctx context.Context, input db.CreateScanInput) (*db.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScan", ctx, input)
	ret0, _ := ret[0].(*db.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScan indicates an expected call of CreateScan.
func (mr *MockScanServicerMockRecorder) CreateScan(ctx, input any) *MockScanServicerCreateScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScan", reflect.TypeOf((*MockScanServicer)(nil).CreateScan), ctx, input)
	return &MockScanServicerCreateScanCall{Call: call}
}

// MockScanServicerCreateScanCall wrap *gomock.Call
type MockScanServicerCreateScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerCreateScanCall) Return(arg0 *db.Scan, arg1 error) *MockScanServicerCreateScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerCreateScanCall) Do(f func(context.Context, db.CreateScanInput) (*db.Scan, error)) *MockScanServicerCreateScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerCreateScanCall) DoAndReturn(f func(context.Context, db.CreateScanInput) (*db.Scan, error)) *MockScanServicerCreateScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteScan mocks base method.
func (m *MockScanServicer) DeleteScan(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScan", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteScan indicates an expected call of DeleteScan.
func (mr *MockScanServicerMockRecorder) DeleteScan(ctx, id any) *MockScanServicerDeleteScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScan", reflect.TypeOf((*MockScanServicer)(nil).DeleteScan), ctx, id)
	return &MockScanServicerDeleteScanCall{Call: call}
}

// MockScanServicerDeleteScanCall wrap *gomock.Call
type MockScanServicerDeleteScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerDeleteScanCall) Return(arg0 error) *MockScanServicerDeleteScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerDeleteScanCall) Do(f func(context.Context, uuid.UUID) error) *MockScanServicerDeleteScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerDeleteScanCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockScanServicerDeleteScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetProfile mocks base method.
func (m *MockScanServicer) GetProfile(ctx context.Context, id string) (*db.ScanProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, id)
	ret0, _ := ret[0].(*db.ScanProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockScanServicerMockRecorder) GetProfile(ctx, id any) *MockScanServicerGetProfileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockScanServicer)(nil).GetProfile), ctx, id)
	return &MockScanServicerGetProfileCall{Call: call}
}

// MockScanServicerGetProfileCall wrap *gomock.Call
type MockScanServicerGetProfileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerGetProfileCall) Return(arg0 *db.ScanProfile, arg1 error) *MockScanServicerGetProfileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerGetProfileCall) Do(f func(context.Context, string) (*db.ScanProfile, error)) *MockScanServicerGetProfileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerGetProfileCall) DoAndReturn(f func(context.Context, string) (*db.ScanProfile, error)) *MockScanServicerGetProfileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetScan mocks base method.
func (m *MockScanServicer) GetScan(ctx context.Context, id uuid.UUID) (*db.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScan", ctx, id)
	ret0, _ := ret[0].(*db.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScan indicates an expected call of GetScan.
func (mr *MockScanServicerMockRecorder) GetScan(ctx, id any) *MockScanServicerGetScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScan", reflect.TypeOf((*MockScanServicer)(nil).GetScan), ctx, id)
	return &MockScanServicerGetScanCall{Call: call}
}

// MockScanServicerGetScanCall wrap *gomock.Call
type MockScanServicerGetScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerGetScanCall) Return(arg0 *db.Scan, arg1 error) *MockScanServicerGetScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerGetScanCall) Do(f func(context.Context, uuid.UUID) (*db.Scan, error)) *MockScanServicerGetScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerGetScanCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.Scan, error)) *MockScanServicerGetScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetScanResults mocks base method.
func (m *MockScanServicer) GetScanResults(ctx context.Context, scanID uuid.UUID, offset, limit int) ([]*db.ScanResult, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanResults", ctx, scanID, offset, limit)
	ret0, _ := ret[0].([]*db.ScanResult)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetScanResults indicates an expected call of GetScanResults.
func (mr *MockScanServicerMockRecorder) GetScanResults(ctx, scanID, offset, limit any) *MockScanServicerGetScanResultsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanResults", reflect.TypeOf((*MockScanServicer)(nil).GetScanResults), ctx, scanID, offset, limit)
	return &MockScanServicerGetScanResultsCall{Call: call}
}

// MockScanServicerGetScanResultsCall wrap *gomock.Call
type MockScanServicerGetScanResultsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerGetScanResultsCall) Return(arg0 []*db.ScanResult, arg1 int64, arg2 error) *MockScanServicerGetScanResultsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerGetScanResultsCall) Do(f func(context.Context, uuid.UUID, int, int) ([]*db.ScanResult, int64, error)) *MockScanServicerGetScanResultsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerGetScanResultsCall) DoAndReturn(f func(context.Context, uuid.UUID, int, int) ([]*db.ScanResult, int64, error)) *MockScanServicerGetScanResultsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetScanSummary mocks base method.
func (m *MockScanServicer) GetScanSummary(ctx context.Context, scanID uuid.UUID) (*db.ScanSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScanSummary", ctx, scanID)
	ret0, _ := ret[0].(*db.ScanSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScanSummary indicates an expected call of GetScanSummary.
func (mr *MockScanServicerMockRecorder) GetScanSummary(ctx, scanID any) *MockScanServicerGetScanSummaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScanSummary", reflect.TypeOf((*MockScanServicer)(nil).GetScanSummary), ctx, scanID)
	return &MockScanServicerGetScanSummaryCall{Call: call}
}

// MockScanServicerGetScanSummaryCall wrap *gomock.Call
type MockScanServicerGetScanSummaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerGetScanSummaryCall) Return(arg0 *db.ScanSummary, arg1 error) *MockScanServicerGetScanSummaryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerGetScanSummaryCall) Do(f func(context.Context, uuid.UUID) (*db.ScanSummary, error)) *MockScanServicerGetScanSummaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerGetScanSummaryCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.ScanSummary, error)) *MockScanServicerGetScanSummaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListScans mocks base method.
func (m *MockScanServicer) ListScans(ctx context.Context, filters db.ScanFilters, offset, limit int) ([]*db.Scan, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScans", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.Scan)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListScans indicates an expected call of ListScans.
func (mr *MockScanServicerMockRecorder) ListScans(ctx, filters, offset, limit any) *MockScanServicerListScansCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScans", reflect.TypeOf((*MockScanServicer)(nil).ListScans), ctx, filters, offset, limit)
	return &MockScanServicerListScansCall{Call: call}
}

// MockScanServicerListScansCall wrap *gomock.Call
type MockScanServicerListScansCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerListScansCall) Return(arg0 []*db.Scan, arg1 int64, arg2 error) *MockScanServicerListScansCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerListScansCall) Do(f func(context.Context, db.ScanFilters, int, int) ([]*db.Scan, int64, error)) *MockScanServicerListScansCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerListScansCall) DoAndReturn(f func(context.Context, db.ScanFilters, int, int) ([]*db.Scan, int64, error)) *MockScanServicerListScansCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StartScan mocks base method.
func (m *MockScanServicer) StartScan(ctx context.Context, id uuid.UUID) (*db.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartScan", ctx, id)
	ret0, _ := ret[0].(*db.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartScan indicates an expected call of StartScan.
func (mr *MockScanServicerMockRecorder) StartScan(ctx, id any) *MockScanServicerStartScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartScan", reflect.TypeOf((*MockScanServicer)(nil).StartScan), ctx, id)
	return &MockScanServicerStartScanCall{Call: call}
}

// MockScanServicerStartScanCall wrap *gomock.Call
type MockScanServicerStartScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerStartScanCall) Return(arg0 *db.Scan, arg1 error) *MockScanServicerStartScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerStartScanCall) Do(f func(context.Context, uuid.UUID) (*db.Scan, error)) *MockScanServicerStartScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerStartScanCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.Scan, error)) *MockScanServicerStartScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StopScan mocks base method.
func (m *MockScanServicer) StopScan(ctx context.Context, id uuid.UUID, errMsg ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range errMsg {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StopScan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopScan indicates an expected call of StopScan.
func (mr *MockScanServicerMockRecorder) StopScan(ctx, id any, errMsg ...any) *MockScanServicerStopScanCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, errMsg...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopScan", reflect.TypeOf((*MockScanServicer)(nil).StopScan), varargs...)
	return &MockScanServicerStopScanCall{Call: call}
}

// MockScanServicerStopScanCall wrap *gomock.Call
type MockScanServicerStopScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerStopScanCall) Return(arg0 error) *MockScanServicerStopScanCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerStopScanCall) Do(f func(context.Context, uuid.UUID, ...string) error) *MockScanServicerStopScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerStopScanCall) DoAndReturn(f func(context.Context, uuid.UUID, ...string) error) *MockScanServicerStopScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateScan mocks base method.
func (m *MockScanServicer) UpdateScan(ctx context.Context, id uuid.UUID, input db.UpdateScanInput) (*db.Scan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScan", ctx, id, input)
	ret0, _ := ret[0].(*db.Scan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScan indicates an expected call of UpdateScan.
func (mr *MockScanServicerMockRecorder) UpdateScan(ctx, id, input any) *MockScanServicerUpdateScanCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScan", reflect.TypeOf((*MockScanServicer)(nil).UpdateScan), ctx, id, input)
	return &MockScanServicerUpdateScanCall{Call: call}
}

// MockScanServicerUpdateScanCall wrap *gomock.Call
type MockScanServicerUpdateScanCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockScanServicerUpdateScanCall) Return(arg0 *db.Scan, arg1 error) *MockScanServicerUpdateScanCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockScanServicerUpdateScanCall) Do(f func(context.Context, uuid.UUID, db.UpdateScanInput) (*db.Scan, error)) *MockScanServicerUpdateScanCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockScanServicerUpdateScanCall) DoAndReturn(f func(context.Context, uuid.UUID, db.UpdateScanInput) (*db.Scan, error)) *MockScanServicerUpdateScanCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
