// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: NetworkServicer)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_network_servicer.go -package mocks github.com/anstrom/scanorama/internal/api/handlers NetworkServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	services "github.com/anstrom/scanorama/internal/services"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkServicer is a mock of NetworkServicer interface.
type MockNetworkServicer struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkServicerMockRecorder
	isgomock struct{}
}

// MockNetworkServicerMockRecorder is the mock recorder for MockNetworkServicer.
type MockNetworkServicerMockRecorder struct {
	mock *MockNetworkServicer
}

// NewMockNetworkServicer creates a new mock instance.
func NewMockNetworkServicer(ctrl *gomock.Controller) *MockNetworkServicer {
	mock := &MockNetworkServicer{ctrl: ctrl}
	mock.recorder = &MockNetworkServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkServicer) EXPECT() *MockNetworkServicerMockRecorder {
	return m.recorder
}

// AddExclusion mocks base method.
func (m *MockNetworkServicer) AddExclusion(ctx context.Context, networkID *uuid.UUID, cidr, reason string) (*db.NetworkExclusion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExclusion", ctx, networkID, cidr, reason)
	ret0, _ := ret[0].(*db.NetworkExclusion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddExclusion indicates an expected call of AddExclusion.
func (mr *MockNetworkServicerMockRecorder) AddExclusion(ctx, networkID, cidr, reason any) *MockNetworkServicerAddExclusionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExclusion", reflect.TypeOf((*MockNetworkServicer)(nil).AddExclusion), ctx, networkID, cidr, reason)
	return &MockNetworkServicerAddExclusionCall{Call: call}
}

// MockNetworkServicerAddExclusionCall wrap *gomock.Call
type MockNetworkServicerAddExclusionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerAddExclusionCall) Return(arg0 *db.NetworkExclusion, arg1 error) *MockNetworkServicerAddExclusionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerAddExclusionCall) Do(f func(context.Context, *uuid.UUID, string, string) (*db.NetworkExclusion, error)) *MockNetworkServicerAddExclusionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerAddExclusionCall) DoAndReturn(f func(context.Context, *uuid.UUID, string, string) (*db.NetworkExclusion, error)) *MockNetworkServicerAddExclusionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateNetwork mocks base method.
func (m *MockNetworkServicer) CreateNetwork(ctx context.Context, name, cidr, description, method string, active, scanEnabled bool) (*db.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, name, cidr, description, method, active, scanEnabled)
	ret0, _ := ret[0].(*db.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockNetworkServicerMockRecorder) CreateNetwork(ctx, name, cidr, description, method, active, scanEnabled any) *MockNetworkServicerCreateNetworkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockNetworkServicer)(nil).CreateNetwork), ctx, name, cidr, description, method, active, scanEnabled)
	return &MockNetworkServicerCreateNetworkCall{Call: call}
}

// MockNetworkServicerCreateNetworkCall wrap *gomock.Call
type MockNetworkServicerCreateNetworkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerCreateNetworkCall) Return(arg0 *db.Network, arg1 error) *MockNetworkServicerCreateNetworkCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerCreateNetworkCall) Do(f func(context.Context, string, string, string, string, bool, bool) (*db.Network, error)) *MockNetworkServicerCreateNetworkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerCreateNetworkCall) DoAndReturn(f func(context.Context, string, string, string, string, bool, bool) (*db.Network, error)) *MockNetworkServicerCreateNetworkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteNetwork mocks base method.
func (m *MockNetworkServicer) DeleteNetwork(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetwork", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNetwork indicates an expected call of DeleteNetwork.
func (mr *MockNetworkServicerMockRecorder) DeleteNetwork(ctx, id any) *MockNetworkServicerDeleteNetworkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetwork", reflect.TypeOf((*MockNetworkServicer)(nil).DeleteNetwork), ctx, id)
	return &MockNetworkServicerDeleteNetworkCall{Call: call}
}

// MockNetworkServicerDeleteNetworkCall wrap *gomock.Call
type MockNetworkServicerDeleteNetworkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerDeleteNetworkCall) Return(arg0 error) *MockNetworkServicerDeleteNetworkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerDeleteNetworkCall) Do(f func(context.Context, uuid.UUID) error) *MockNetworkServicerDeleteNetworkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerDeleteNetworkCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockNetworkServicerDeleteNetworkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGlobalExclusions mocks base method.
func (m *MockNetworkServicer) GetGlobalExclusions(ctx context.Context) ([]*db.NetworkExclusion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGlobalExclusions", ctx)
	ret0, _ := ret[0].([]*db.NetworkExclusion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGlobalExclusions indicates an expected call of GetGlobalExclusions.
func (mr *MockNetworkServicerMockRecorder) GetGlobalExclusions(ctx any) *MockNetworkServicerGetGlobalExclusionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGlobalExclusions", reflect.TypeOf((*MockNetworkServicer)(nil).GetGlobalExclusions), ctx)
	return &MockNetworkServicerGetGlobalExclusionsCall{Call: call}
}

// MockNetworkServicerGetGlobalExclusionsCall wrap *gomock.Call
type MockNetworkServicerGetGlobalExclusionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerGetGlobalExclusionsCall) Return(arg0 []*db.NetworkExclusion, arg1 error) *MockNetworkServicerGetGlobalExclusionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerGetGlobalExclusionsCall) Do(f func(context.Context) ([]*db.NetworkExclusion, error)) *MockNetworkServicerGetGlobalExclusionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerGetGlobalExclusionsCall) DoAndReturn(f func(context.Context) ([]*db.NetworkExclusion, error)) *MockNetworkServicerGetGlobalExclusionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetNetworkByID mocks base method.
func (m *MockNetworkServicer) GetNetworkByID(ctx context.Context, id uuid.UUID) (*services.NetworkWithExclusions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByID", ctx, id)
	ret0, _ := ret[0].(*services.NetworkWithExclusions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByID indicates an expected call of GetNetworkByID.
func (mr *MockNetworkServicerMockRecorder) GetNetworkByID(ctx, id any) *MockNetworkServicerGetNetworkByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByID", reflect.TypeOf((*MockNetworkServicer)(nil).GetNetworkByID), ctx, id)
	return &MockNetworkServicerGetNetworkByIDCall{Call: call}
}

// MockNetworkServicerGetNetworkByIDCall wrap *gomock.Call
type MockNetworkServicerGetNetworkByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerGetNetworkByIDCall) Return(arg0 *services.NetworkWithExclusions, arg1 error) *MockNetworkServicerGetNetworkByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerGetNetworkByIDCall) Do(f func(context.Context, uuid.UUID) (*services.NetworkWithExclusions, error)) *MockNetworkServicerGetNetworkByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerGetNetworkByIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (*services.NetworkWithExclusions, error)) *MockNetworkServicerGetNetworkByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetNetworkExclusions mocks base method.
func (m *MockNetworkServicer) GetNetworkExclusions(ctx context.Context, networkID uuid.UUID) ([]*db.NetworkExclusion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkExclusions", ctx, networkID)
	ret0, _ := ret[0].([]*db.NetworkExclusion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkExclusions indicates an expected call of GetNetworkExclusions.
func (mr *MockNetworkServicerMockRecorder) GetNetworkExclusions(ctx, networkID any) *MockNetworkServicerGetNetworkExclusionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkExclusions", reflect.TypeOf((*MockNetworkServicer)(nil).GetNetworkExclusions), ctx, networkID)
	return &MockNetworkServicerGetNetworkExclusionsCall{Call: call}
}

// MockNetworkServicerGetNetworkExclusionsCall wrap *gomock.Call
type MockNetworkServicerGetNetworkExclusionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerGetNetworkExclusionsCall) Return(arg0 []*db.NetworkExclusion, arg1 error) *MockNetworkServicerGetNetworkExclusionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerGetNetworkExclusionsCall) Do(f func(context.Context, uuid.UUID) ([]*db.NetworkExclusion, error)) *MockNetworkServicerGetNetworkExclusionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerGetNetworkExclusionsCall) DoAndReturn(f func(context.Context, uuid.UUID) ([]*db.NetworkExclusion, error)) *MockNetworkServicerGetNetworkExclusionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetNetworkStats mocks base method.
func (m *MockNetworkServicer) GetNetworkStats(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkStats", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkStats indicates an expected call of GetNetworkStats.
func (mr *MockNetworkServicerMockRecorder) GetNetworkStats(ctx any) *MockNetworkServicerGetNetworkStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkStats", reflect.TypeOf((*MockNetworkServicer)(nil).GetNetworkStats), ctx)
	return &MockNetworkServicerGetNetworkStatsCall{Call: call}
}

// MockNetworkServicerGetNetworkStatsCall wrap *gomock.Call
type MockNetworkServicerGetNetworkStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerGetNetworkStatsCall) Return(arg0 map[string]any, arg1 error) *MockNetworkServicerGetNetworkStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerGetNetworkStatsCall) Do(f func(context.Context) (map[string]any, error)) *MockNetworkServicerGetNetworkStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerGetNetworkStatsCall) DoAndReturn(f func(context.Context) (map[string]any, error)) *MockNetworkServicerGetNetworkStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListNetworks mocks base method.
func (m *MockNetworkServicer) ListNetworks(ctx context.Context, activeOnly bool) ([]*db.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNetworks", ctx, activeOnly)
	ret0, _ := ret[0].([]*db.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNetworks indicates an expected call of ListNetworks.
func (mr *MockNetworkServicerMockRecorder) ListNetworks(ctx, activeOnly any) *MockNetworkServicerListNetworksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNetworks", reflect.TypeOf((*MockNetworkServicer)(nil).ListNetworks), ctx, activeOnly)
	return &MockNetworkServicerListNetworksCall{Call: call}
}

// MockNetworkServicerListNetworksCall wrap *gomock.Call
type MockNetworkServicerListNetworksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerListNetworksCall) Return(arg0 []*db.Network, arg1 error) *MockNetworkServicerListNetworksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerListNetworksCall) Do(f func(context.Context, bool) ([]*db.Network, error)) *MockNetworkServicerListNetworksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerListNetworksCall) DoAndReturn(f func(context.Context, bool) ([]*db.Network, error)) *MockNetworkServicerListNetworksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveExclusion mocks base method.
func (m *MockNetworkServicer) RemoveExclusion(ctx context.Context, exclusionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveExclusion", ctx, exclusionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveExclusion indicates an expected call of RemoveExclusion.
func (mr *MockNetworkServicerMockRecorder) RemoveExclusion(ctx, exclusionID any) *MockNetworkServicerRemoveExclusionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveExclusion", reflect.TypeOf((*MockNetworkServicer)(nil).RemoveExclusion), ctx, exclusionID)
	return &MockNetworkServicerRemoveExclusionCall{Call: call}
}

// MockNetworkServicerRemoveExclusionCall wrap *gomock.Call
type MockNetworkServicerRemoveExclusionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerRemoveExclusionCall) Return(arg0 error) *MockNetworkServicerRemoveExclusionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerRemoveExclusionCall) Do(f func(context.Context, uuid.UUID) error) *MockNetworkServicerRemoveExclusionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerRemoveExclusionCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockNetworkServicerRemoveExclusionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateNetwork mocks base method.
func (m *MockNetworkServicer) UpdateNetwork(ctx context.Context, id uuid.UUID, name, cidr, description, method string, active bool) (*db.Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNetwork", ctx, id, name, cidr, description, method, active)
	ret0, _ := ret[0].(*db.Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNetwork indicates an expected call of UpdateNetwork.
func (mr *MockNetworkServicerMockRecorder) UpdateNetwork(ctx, id, name, cidr, description, method, active any) *MockNetworkServicerUpdateNetworkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNetwork", reflect.TypeOf((*MockNetworkServicer)(nil).UpdateNetwork), ctx, id, name, cidr, description, method, active)
	return &MockNetworkServicerUpdateNetworkCall{Call: call}
}

// MockNetworkServicerUpdateNetworkCall wrap *gomock.Call
type MockNetworkServicerUpdateNetworkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockNetworkServicerUpdateNetworkCall) Return(arg0 *db.Network, arg1 error) *MockNetworkServicerUpdateNetworkCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockNetworkServicerUpdateNetworkCall) Do(f func(context.Context, uuid.UUID, string, string, string, string, bool) (*db.Network, error)) *MockNetworkServicerUpdateNetworkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockNetworkServicerUpdateNetworkCall) DoAndReturn(f func(context.Context, uuid.UUID, string, string, string, string, bool) (*db.Network, error)) *MockNetworkServicerUpdateNetworkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
