// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anstrom/scanorama/internal/api/handlers (interfaces: HostServicer)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/mock_host_servicer.go -package mocks github.com/anstrom/scanorama/internal/api/handlers HostServicer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/anstrom/scanorama/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockHostServicer is a mock of HostServicer interface.
type MockHostServicer struct {
	ctrl     *gomock.Controller
	recorder *MockHostServicerMockRecorder
	isgomock struct{}
}

// MockHostServicerMockRecorder is the mock recorder for MockHostServicer.
type MockHostServicerMockRecorder struct {
	mock *MockHostServicer
}

// NewMockHostServicer creates a new mock instance.
func NewMockHostServicer(ctrl *gomock.Controller) *MockHostServicer {
	mock := &MockHostServicer{ctrl: ctrl}
	mock.recorder = &MockHostServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostServicer) EXPECT() *MockHostServicerMockRecorder {
	return m.recorder
}

// CreateHost mocks base method.
func (m *MockHostServicer) CreateHost(ctx context.Context, input db.CreateHostInput) (*db.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHost", ctx, input)
	ret0, _ := ret[0].(*db.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHost indicates an expected call of CreateHost.
func (mr *MockHostServicerMockRecorder) CreateHost(ctx, input any) *MockHostServicerCreateHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHost", reflect.TypeOf((*MockHostServicer)(nil).CreateHost), ctx, input)
	return &MockHostServicerCreateHostCall{Call: call}
}

// MockHostServicerCreateHostCall wrap *gomock.Call
type MockHostServicerCreateHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostServicerCreateHostCall) Return(arg0 *db.Host, arg1 error) *MockHostServicerCreateHostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostServicerCreateHostCall) Do(f func(context.Context, db.CreateHostInput) (*db.Host, error)) *MockHostServicerCreateHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostServicerCreateHostCall) DoAndReturn(f func(context.Context, db.CreateHostInput) (*db.Host, error)) *MockHostServicerCreateHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteHost mocks base method.
func (m *MockHostServicer) DeleteHost(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHost", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHost indicates an expected call of DeleteHost.
func (mr *MockHostServicerMockRecorder) DeleteHost(ctx, id any) *MockHostServicerDeleteHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHost", reflect.TypeOf((*MockHostServicer)(nil).DeleteHost), ctx, id)
	return &MockHostServicerDeleteHostCall{Call: call}
}

// MockHostServicerDeleteHostCall wrap *gomock.Call
type MockHostServicerDeleteHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostServicerDeleteHostCall) Return(arg0 error) *MockHostServicerDeleteHostCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostServicerDeleteHostCall) Do(f func(context.Context, uuid.UUID) error) *MockHostServicerDeleteHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostServicerDeleteHostCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockHostServicerDeleteHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHost mocks base method.
func (m *MockHostServicer) GetHost(ctx context.Context, id uuid.UUID) (*db.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost", ctx, id)
	ret0, _ := ret[0].(*db.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHost indicates an expected call of GetHost.
func (mr *MockHostServicerMockRecorder) GetHost(ctx, id any) *MockHostServicerGetHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockHostServicer)(nil).GetHost), ctx, id)
	return &MockHostServicerGetHostCall{Call: call}
}

// MockHostServicerGetHostCall wrap *gomock.Call
type MockHostServicerGetHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostServicerGetHostCall) Return(arg0 *db.Host, arg1 error) *MockHostServicerGetHostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostServicerGetHostCall) Do(f func(context.Context, uuid.UUID) (*db.Host, error)) *MockHostServicerGetHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostServicerGetHostCall) DoAndReturn(f func(context.Context, uuid.UUID) (*db.Host, error)) *MockHostServicerGetHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetHostScans mocks base method.
func (m *MockHostServicer) GetHostScans(ctx context.Context, hostID uuid.UUID, offset, limit int) ([]*db.Scan, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostScans", ctx, hostID, offset, limit)
	ret0, _ := ret[0].([]*db.Scan)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHostScans indicates an expected call of GetHostScans.
func (mr *MockHostServicerMockRecorder) GetHostScans(ctx, hostID, offset, limit any) *MockHostServicerGetHostScansCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostScans", reflect.TypeOf((*MockHostServicer)(nil).GetHostScans), ctx, hostID, offset, limit)
	return &MockHostServicerGetHostScansCall{Call: call}
}

// MockHostServicerGetHostScansCall wrap *gomock.Call
type MockHostServicerGetHostScansCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostServicerGetHostScansCall) Return(arg0 []*db.Scan, arg1 int64, arg2 error) *MockHostServicerGetHostScansCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostServicerGetHostScansCall) Do(f func(context.Context, uuid.UUID, int, int) ([]*db.Scan, int64, error)) *MockHostServicerGetHostScansCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostServicerGetHostScansCall) DoAndReturn(f func(context.Context, uuid.UUID, int, int) ([]*db.Scan, int64, error)) *MockHostServicerGetHostScansCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListHosts mocks base method.
func (m *MockHostServicer) ListHosts(ctx context.Context, filters *db.HostFilters, offset, limit int) ([]*db.Host, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHosts", ctx, filters, offset, limit)
	ret0, _ := ret[0].([]*db.Host)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListHosts indicates an expected call of ListHosts.
func (mr *MockHostServicerMockRecorder) ListHosts(ctx, filters, offset, limit any) *MockHostServicerListHostsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHosts", reflect.TypeOf((*MockHostServicer)(nil).ListHosts), ctx, filters, offset, limit)
	return &MockHostServicerListHostsCall{Call: call}
}

// MockHostServicerListHostsCall wrap *gomock.Call
type MockHostServicerListHostsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostServicerListHostsCall) Return(arg0 []*db.Host, arg1 int64, arg2 error) *MockHostServicerListHostsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostServicerListHostsCall) Do(f func(context.Context, *db.HostFilters, int, int) ([]*db.Host, int64, error)) *MockHostServicerListHostsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostServicerListHostsCall) DoAndReturn(f func(context.Context, *db.HostFilters, int, int) ([]*db.Host, int64, error)) *MockHostServicerListHostsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateHost mocks base method.
func (m *MockHostServicer) UpdateHost(ctx context.Context, id uuid.UUID, input db.UpdateHostInput) (*db.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHost", ctx, id, input)
	ret0, _ := ret[0].(*db.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateHost indicates an expected call of UpdateHost.
func (mr *MockHostServicerMockRecorder) UpdateHost(ctx, id, input any) *MockHostServicerUpdateHostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHost", reflect.TypeOf((*MockHostServicer)(nil).UpdateHost), ctx, id, input)
	return &MockHostServicerUpdateHostCall{Call: call}
}

// MockHostServicerUpdateHostCall wrap *gomock.Call
type MockHostServicerUpdateHostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHostServicerUpdateHostCall) Return(arg0 *db.Host, arg1 error) *MockHostServicerUpdateHostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHostServicerUpdateHostCall) Do(f func(context.Context, uuid.UUID, db.UpdateHostInput) (*db.Host, error)) *MockHostServicerUpdateHostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHostServicerUpdateHostCall) DoAndReturn(f func(context.Context, uuid.UUID, db.UpdateHostInput) (*db.Host, error)) *MockHostServicerUpdateHostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
