version: "2"

run:
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: "1.24.6"

linters:
  default: none
  enable:
    # Error detection
    - errcheck
    - gosec
    - govet

    # Code quality
    - staticcheck
    - ineffassign
    - unconvert
    - unparam
    - unused

    # Performance
    - prealloc

    # Style and formatting
    - misspell
    - whitespace

    # Bugs and correctness
    - gocritic
    - goconst
    - dupl
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

    # Complexity
    - gocyclo
    - funlen
    - lll

    # Documentation
    - godot

    # Best practices
    - copyloopvar
    - mnd
    - nestif
    - predeclared
    - nolintlint

  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint

    gocyclo:
      min-complexity: 15

    funlen:
      lines: 100
      statements: 50

    lll:
      line-length: 120
      tab-width: 4

    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "8"
        - "10"
        - "16"
        - "32"
        - "64"
        - "80"
        - "443"
        - "1024"
        - "8080"

    nestif:
      min-complexity: 5

    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false

    misspell:
      locale: US

    staticcheck:
      checks: ["all"]

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - errcheck # Allow unchecked errors in tests
          - gosec # Allow security warnings in test files
          - dupl # Allow duplicate code patterns in tests
          - gocyclo # Allow high complexity in comprehensive tests
          - goconst # Don't require constants for test strings
          - mnd # Allow magic numbers in tests

  #     - path: cmd/.*main\.go
  #       linters:
  #         - funlen
  #         - mnd

  #     - path: ".*\\.pb\\.go"
  #       linters:
  #         - lll

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
