version: "2"

run:
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: "1.24.6"

linters:
  default: none
  enable:
    # Error detection
    - errcheck
    - gosec
    - govet

    # Code quality
    - staticcheck
    - ineffassign
    - unconvert
    - unparam
    - unused

    # Performance
    - prealloc

    # Style and formatting
    - misspell
    - whitespace

    # Bugs and correctness
    - gocritic
    - goconst
    - dupl
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

    # Complexity
    - gocyclo
    - funlen
    - lll

    # Documentation
    - godot

    # Best practices
    - copyloopvar
    - mnd
    - nestif
    - predeclared
    - nolintlint

  settings:
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint

    gocyclo:
      min-complexity: 15

    funlen:
      lines: 100
      statements: 50

    lll:
      line-length: 120
      tab-width: 4

    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "8"
        - "10"
        - "16"
        - "32"
        - "64"
        - "80"
        - "443"
        - "1024"
        - "8080"

    nestif:
      min-complexity: 5

    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false

    misspell:
      locale: US

    staticcheck:
      checks: ["all"]

  exclusions:
    rules:
      # ====================
      # TEST FILE EXCLUSIONS
      # ====================
      - path: _test\.go
        linters:
          - funlen
          - errcheck # Allow unchecked errors in tests
          - gosec # Allow security warnings in test files
          - dupl # Allow duplicate code patterns in tests
          - gocyclo # Allow high complexity in comprehensive tests
          - goconst # Don't require constants for test strings
          - mnd # Allow magic numbers in tests

      # ========================
      # SWAGGER/API DOCUMENTATION EXCLUSIONS
      # ========================
      # Strategy: Use code-first approach with Swaggo annotations
      # - Generated files in docs/swagger/ are completely excluded
      # - Annotation files have targeted exclusions for doc-specific issues
      # - All Swagger annotations (// @*) are excluded from godot globally

      # Generated Swagger documentation files (auto-generated by swag)
      - path: docs/swagger/.*
        linters:
          - godot # Generated docs don't follow comment rules
          - misspell # Generated code may use different spellings
          - lll # Generated code may have very long lines
          - funlen # Generated functions can be extremely long
          - gocyclo # Generated code complexity doesn't matter
          - unused # Generated code exports may appear unused
          - staticcheck # Skip static analysis on generated files
          - goconst # Generated code may repeat strings
          - mnd # Generated code may have magic numbers
          - dupl # Generated code often has duplication
          - ineffassign # Generated code assignment patterns
          - unconvert # Generated code conversions
          - unparam # Generated code parameters
          - prealloc # Generated code allocations
          - whitespace # Generated code formatting
          - gocritic # Generated code patterns
          - bodyclose # Generated code HTTP handling
          - rowserrcheck # Generated code error handling
          - sqlclosecheck # Generated code SQL handling
          - copyloopvar # Generated code variable usage

      # Swagger annotation definition files (manual, contains type definitions)
      - path: docs/swagger_docs\.go
        linters:
          - godot # Swagger annotations don't need periods
          - misspell # Allow technical terms like "cancelled"
          - lll # Documentation comments can be long
          - funlen # Documentation functions are placeholders
          - unused # Documentation functions may not be called
          - goconst # Documentation may repeat example strings
          - mnd # Documentation may use example numbers
          - dupl # Documentation may have similar examples

      # Global exclusion for ALL Swagger annotations across the entire codebase
      # This ensures any file with Swagger annotations won't trigger godot errors
      - linters:
          - godot # Swagger annotations (@Summary, @Router, etc.) don't need periods
        source: "// @"

      # ========================
      # API-SPECIFIC EXCLUSIONS
      # ========================
      # Global exclusion for "cancelled" vs "canceled" in API contexts
      - linters:
          - misspell
        text: "cancelled"

  #     - path: cmd/.*main\.go
  #       linters:
  #         - funlen
  #         - mnd

  #     - path: ".*\\.pb\\.go"
  #       linters:
  #         - lll

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
