version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/scanorama
    binary: scanorama
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'main.version={{.Version}}'
      - -X 'main.commit={{.Commit}}'
      - -X 'main.buildTime={{.Date}}'

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksums:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  prerelease: auto
