# Dockerfile linting configuration
# See https://github.com/hadolint/hadolint#configure

# Ignored rules
ignored:
  # Allow apt-get update and install in same layer
  - DL3008
  # Allow pip install without version pinning
  - DL3013
  # Allow `npm install` without pinned versions
  - DL3016
  # Allow using :latest tag
  - DL3007

# Configure rules
trustedRegistries:
  - docker.io
  - ghcr.io

# Label schema configuration
label-schema:
  required:
    - maintainer

# Shell configuration
override:
  shell:
    - code: DL4006  # Set pipefail
      level: warning

# Custom rules severity
failure-threshold: style
