# Redocly configuration for Scanorama API documentation
# Simplified configuration to avoid validation warnings

extends:
  - recommended

rules:
  # Security rules - customize to allow public endpoints
  security-defined:
    severity: error
    exceptions:
      # Public endpoints that don't require authentication
      - /health#get
      - /status#get
      - /version#get
      - /metrics#get

  # Response coverage rules
  operation-2xx-response: error
  operation-4xx-response:
    severity: warn
    exceptions:
      # Public endpoints may not need 4xx responses
      - /health#get
      - /status#get
      - /version#get

  # Operation rules
  operation-operationId: error
  operation-summary: warn
  operation-description: warn

  # Disable overly strict rules for our use case
  operation-tag-defined: off
  no-path-trailing-slash: off
  operation-singular-tag: off

  # Path and parameter rules
  path-declaration-must-exist: error
  path-not-include-query: error
  path-parameters-defined: error

  # Schema and model rules
  no-unresolved-refs: error
  no-enum-type-mismatch: error

  # Documentation quality rules
  info-contact: warn
  info-license: warn
