# Scanorama Configuration File
# Production-ready configuration with proper PostgreSQL setup

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

  cors:
    enabled: true
    allowed_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "X-Requested-With"]

  rate_limit:
    enabled: false

# Database Configuration
database:
  host: "localhost"
  port: 5432
  database: "scanorama_dev"
  username: "scanorama_dev"
  password: "dev_password"

  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: "1h"

  ssl_mode: "disable"
  auto_migrate: false
  migration_timeout: "5m"

# Scanning Configuration
scanning:
  default_timeout: "5m"
  default_ports: "80,443,22,21,25,53,110,143,993,995,8080,8443"
  max_concurrent_scans: 3

  discovery:
    ping_timeout: "3s"
    max_hosts_per_scan: 254

  port_scan:
    timeout: "1s"
    max_concurrent_ports: 50
    scan_delay: "10ms"

  service_detection:
    enabled: true
    timeout: "10s"
    max_probes: 3

# Network Configuration
network:
  default_networks:
    - "192.168.1.0/24"
    - "10.0.0.0/24"

  excluded_networks:
    - "127.0.0.0/8"
    - "169.254.0.0/16"
    - "224.0.0.0/4"

  interface: "auto"

# Logging Configuration
logging:
  level: "info"
  format: "text"
  output: "stdout"

  components:
    database: "info"
    scanner: "info"
    api: "info"
    discovery: "info"

# Security Configuration
security:
  api:
    enabled: false

  admin:
    enabled: true
    require_auth: false

  scanning:
    require_authorization: false
    max_scan_size: "1000"
    scan_approval_required: false

# Performance Configuration
performance:
  worker_pool:
    size: 5
    queue_size: 100
    retry_attempts: 3
    retry_delay: "30s"

  memory:
    max_scan_results: 10000
    result_cache_ttl: "1h"

  timeouts:
    scan_job: "30m"
    database_query: "30s"
    external_api: "10s"

# Monitoring Configuration
monitoring:
  metrics:
    enabled: true
    endpoint: "/metrics"
    interval: "30s"

  health:
    enabled: true
    endpoint: "/health"

  alerts:
    enabled: false

# Storage Configuration
storage:
  retention:
    scan_results: "90d"
    host_data: "365d"
    logs: "30d"

  cleanup:
    enabled: true
    interval: "24h"
    batch_size: 1000

# Feature Flags
features:
  experimental:
    advanced_scanning: false

  beta:
    web_ui: true
    api_v2: false

  legacy:
    api_v1_compat: true

# Development Settings
development:
  debug: false
  hot_reload: false

  testing:
    mock_scans: false
    test_data_enabled: false

  profiling:
    enabled: false
