# Scanorama Development Configuration
# Optimized for local development and testing

# Daemon Process Configuration
daemon:
  # PID file location for development
  pid_file: "./scanorama.pid"

  # Working directory (current directory for dev)
  work_dir: "."

  # Don't change user/group in development
  user: ""
  group: ""

  # Don't fork to background in development
  daemonize: false

  # Graceful shutdown timeout
  shutdown_timeout: "10s"

# Database Configuration - Local PostgreSQL
database:
  host: "localhost"
  port: 5432
  database: "scanorama_dev"
  username: "scanorama_dev"
  password: "dev_password"
  ssl_mode: "disable"  # Disable SSL for local development

  # Smaller connection pool for development
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: "5m"
  conn_max_idle_time: "5m"

# Scanning Configuration - Development defaults
scanning:
  # Fewer workers for development
  worker_pool_size: 5

  # Shorter intervals for faster testing
  default_interval: "30m"

  # Shorter timeout for development
  max_scan_timeout: "5m"

  # Common development ports
  default_ports: "22,80,443,8080,8443,9000,3000,5000"

  # Use connect scan (doesn't require root)
  default_scan_type: "connect"

  # Smaller concurrent targets for development
  max_concurrent_targets: 10

  # Enable service detection
  enable_service_detection: true

  # Disable OS detection (requires root)
  enable_os_detection: false

  # Faster retry configuration for development
  retry:
    max_retries: 2
    retry_delay: "10s"
    backoff_multiplier: 1.5

  # More permissive rate limiting for development
  rate_limit:
    enabled: true
    requests_per_second: 50
    burst_size: 100

# API Server Configuration - Development settings
api:
  enabled: true
  listen_addr: "127.0.0.1"
  port: 8080

  # Disable TLS for development
  tls:
    enabled: false

  # No API key required for development
  api_key: ""

  # Permissive CORS for development
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]

  # Shorter timeout for development
  request_timeout: "15s"

  # Standard request size limit
  max_request_size: 1048576

# Logging Configuration - Verbose for development
logging:
  # Debug level for development
  level: "debug"

  # Human-readable text format
  format: "text"

  # Output to stdout for development
  output: "stdout"

  # No rotation needed for development
  rotation:
    enabled: false

  # Disable structured logging for better readability
  structured: false

  # Enable API request logging
  request_logging: true
