package enrichment

import (
	"net"
	"regexp"
	"strings"
)

// dhcpPrefixes are leftmost-label prefixes commonly generated by DHCP servers.
var dhcpPrefixes = []string{"dhcp-", "host-", "ip-", "client-"}

// noiseSuffixes are domain-label substrings generated by ISPs or DHCP infrastructure.
var noiseSuffixes = []string{".dynamic.", ".dhcp.", ".broadband."}

// ipLiteralPattern matches embedded IP-style octets separated by hyphens or dots,
// e.g. "192-168-1-50" or "10.0.0.1" appearing inside a hostname label.
var ipLiteralPattern = regexp.MustCompile(`\b\d{1,3}[-.]\d{1,3}[-.]\d{1,3}[-.]\d{1,3}\b`)

// DNSNameIsUsable returns true when the PTR name is likely a stable, human-assigned
// hostname rather than a DHCP-generated or ISP-generated artifact.
//
// Names are rejected when they:
//   - Are a bare IP address literal
//   - Contain an IP literal embedded with hyphens (e.g. 192-168-1-50)
//   - Have a leftmost label starting with a DHCP-generated prefix (dhcp-, host-, ip-, client-)
//   - Contain an ISP/DHCP infrastructure fragment (.dynamic., .dhcp., .broadband.)
//   - Consist entirely of numeric labels (e.g. reversed-PTR arpa form "1.0.168.192")
func DNSNameIsUsable(name string) bool {
	lower := strings.ToLower(strings.TrimSuffix(name, "."))

	if lower == "" {
		return false
	}

	// Bare IP address.
	if net.ParseIP(lower) != nil {
		return false
	}

	// IP literal embedded in the hostname.
	if ipLiteralPattern.MatchString(lower) {
		return false
	}

	// DHCP-generated prefix on the leftmost label.
	leftmost, _, _ := strings.Cut(lower, ".")
	for _, pfx := range dhcpPrefixes {
		if strings.HasPrefix(leftmost, pfx) {
			return false
		}
	}

	// ISP/infrastructure domain fragments anywhere in the FQDN.
	for _, sfx := range noiseSuffixes {
		if strings.Contains(lower, sfx) {
			return false
		}
	}

	// All labels are purely numeric (e.g. reversed-IP PTR: "1.0.168.192.in-addr.arpa").
	labels := strings.Split(lower, ".")
	allNumeric := true
	for _, label := range labels {
		for _, ch := range label {
			if ch < '0' || ch > '9' {
				allNumeric = false
				break
			}
		}
		if !allNumeric {
			break
		}
	}
	return !allNumeric
}
