name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/anstrom/*

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Verify Go environment
        run: |
          echo "Go version: $(go version)"
          echo "Go env GOOS: $(go env GOOS)"
          echo "Go env GOARCH: $(go env GOARCH)"
          echo "Go env GOMODCACHE: $(go env GOMODCACHE)"
          echo "GOPRIVATE: ${GOPRIVATE}"

      - name: Build project
        run: make build

      - name: Run tests
        run: make test

      - name: Test binary
        run: ./build/scanorama -version
