name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/anstrom/*

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"
          cache: false

      - name: Clean module cache
        run: |
          go clean -modcache
          rm -rf $(go env GOMODCACHE)

      - name: Install dependencies
        run: |
          go mod download -x
          go mod verify
          go mod tidy

      - name: Verify Go environment
        run: |
          echo "Go version: $(go version)"
          echo "Go env GOOS: $(go env GOOS)"
          echo "Go env GOARCH: $(go env GOARCH)"
          echo "Go env GOMODCACHE: $(go env GOMODCACHE)"
          echo "GOPRIVATE: ${GOPRIVATE}"
          echo "Module info:"
          go list -m all
          echo "Package structure:"
          go list ./...

      - name: Verify internal package
        run: |
          echo "Checking internal package exports:"
          go doc ./internal
          echo "Checking specific functions:"
          grep -n "func.*RunScanWithContext\|func.*PrintResults\|func.*RunScan" internal/scan.go || echo "Functions not found"

      - name: Install nmap
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap
          nmap --version

      - name: Build project
        run: make build

      - name: Run tests
        run: make test

      - name: Test binary
        run: ./build/scanorama -version
