name: Security

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  GO_VERSION: "1.25.1"

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run Go vulnerability check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: Check for known vulnerabilities in dependencies
        run: |
          go list -json -deps ./... | jq -r '.Module | select(.Path != null) | .Path + "@" + .Version' | sort -u > deps.txt
          echo "📦 Dependencies scanned:"
          cat deps.txt
          echo "✅ Vulnerability scan completed"

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: go
          config: |
            paths-ignore:
              - "**/*_test.go"
              - "**/testdata/**"
              - "**/vendor/**"

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:go"

  security-hardening:
    name: Security Hardening Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Check for hardcoded secrets patterns
        run: |
          echo "🔍 Checking for potential hardcoded secrets..."

          # Check for common secret patterns
          if grep -r -i "password.*=" --include="*.go" . | grep -v "_test.go" | grep -v "example\|template\|config\.template"; then
            echo "⚠️ Found potential hardcoded passwords"
          fi

          if grep -r -i "api[_-]key.*=" --include="*.go" . | grep -v "_test.go" | grep -v "example\|template"; then
            echo "⚠️ Found potential hardcoded API keys"
          fi

          if grep -r -i "secret.*=" --include="*.go" . | grep -v "_test.go" | grep -v "example\|template"; then
            echo "⚠️ Found potential hardcoded secrets"
          fi

          echo "✅ Secret pattern check completed"

      - name: Check file permissions
        run: |
          echo "🔒 Checking file permissions..."

          # Find files with overly permissive permissions
          find . -type f -perm /o+w -not -path "./.git/*" -not -path "./build/*" -not -path "./dist/*" | while read file; do
            echo "⚠️ World-writable file found: $file"
          done

          # Check for executable files that shouldn't be
          find . -name "*.go" -perm /a+x -not -path "./.git/*" | while read file; do
            echo "⚠️ Executable Go file found: $file"
          done

          echo "✅ File permission check completed"

  npm-audit:
    name: NPM Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: |
          echo "🔍 Running npm security audit..."
          npm audit --audit-level moderate
          echo "✅ NPM audit completed"

      - name: Check for outdated packages
        run: |
          echo "📦 Checking for outdated packages..."
          npm outdated || true
          echo "ℹ️ Outdated package check completed"

  license-compliance:
    name: License Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Check Go module licenses
        run: |
          echo "📄 Checking Go module licenses..."

          # Install go-licenses tool
          go install github.com/google/go-licenses@latest

          # Check licenses (allow common permissive licenses)
          go-licenses check ./... --allowed_licenses=Apache-2.0,MIT,BSD-2-Clause,BSD-3-Clause,ISC || {
            echo "❌ License compliance check failed"
            echo "Run 'go-licenses report ./...' to see all licenses"
            exit 1
          }

          echo "✅ License compliance check passed"

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs:
      [
        vulnerability-scan,
        codeql-analysis,
        security-hardening,
        npm-audit,
        license-compliance,
      ]
    if: always()
    steps:
      - name: Security pipeline summary
        run: |
          echo "🔒 Security Pipeline Summary:"
          echo "- Vulnerability Scan: ${{ needs.vulnerability-scan.result }}"
          echo "- CodeQL Analysis: ${{ needs.codeql-analysis.result }}"
          echo "- Security Hardening: ${{ needs.security-hardening.result }}"
          echo "- NPM Audit: ${{ needs.npm-audit.result }}"
          echo "- License Compliance: ${{ needs.license-compliance.result }}"

          # Count failures
          FAILURES=0
          if [[ "${{ needs.vulnerability-scan.result }}" == "failure" ]]; then
            echo "❌ Vulnerability scan failed"
            FAILURES=$((FAILURES + 1))
          fi
          if [[ "${{ needs.codeql-analysis.result }}" == "failure" ]]; then
            echo "❌ CodeQL analysis failed"
            FAILURES=$((FAILURES + 1))
          fi
          if [[ "${{ needs.security-hardening.result }}" == "failure" ]]; then
            echo "❌ Security hardening check failed"
            FAILURES=$((FAILURES + 1))
          fi
          if [[ "${{ needs.license-compliance.result }}" == "failure" ]]; then
            echo "❌ License compliance check failed"
            FAILURES=$((FAILURES + 1))
          fi

          if [ "$FAILURES" -gt 0 ]; then
            echo "⚠️ $FAILURES security check(s) failed"
            echo "Please review the failed jobs and address security issues"
            exit 1
          fi

          echo "✅ All security checks passed!"
