name: Test and Lint

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  statuses: write # Required for codecov

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go version

      - name: Build development image
        run: docker build -t scanorama-dev -f Dockerfile.dev .

      - name: Build test environment
        run: test/docker/test-env.sh build

      - name: Run linter
        run: make docker-lint

      - name: Run tests
        run: |
          make test-env-clean
          make docker-test

      - name: Run coverage
        run: |
          make test-env-clean
          make docker-coverage
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.*
          if-no-files-found: warn

      - name: Clean up
        if: always()
        run: |
          make test-env-clean
          make docker-clean
          docker system prune -af --volumes
